import type { AndroidSymbol } from 'expo-symbols';

// Same meaning as the iOS symbol; Material Symbols are bundled by expo-symbols.
const symbols: Record<string, AndroidSymbol> = {
  'bubble.left.and.bubble.right': 'forum',
  'line.3.horizontal.decrease': 'filter_list',
  'quote.bubble': 'format_quote',
  'text.badge.plus': 'edit_note',
  trash: 'delete',
  'arrow.clockwise': 'refresh',
  'arrow.up': 'arrow_upward',
  'arrow.right': 'arrow_forward',
  'arrow.triangle.2.circlepath': 'sync',
  'arrow.triangle.branch': 'fork_right',
  'arrow.up.right': 'north_east',
  'arrow.up.right.square': 'open_in_new',
  banknote: 'payments',
  'books.vertical': 'library_books',
  'building.2': 'domain',
  'building.columns': 'account_balance',
  calendar: 'calendar_month',
  'chart.bar.doc.horizontal': 'bar_chart',
  checkmark: 'check',
  'checkmark.seal': 'verified',
  'checkmark.square': 'check_box',
  'chevron.down': 'expand_more',
  'chevron.left': 'chevron_left',
  'chevron.left.forwardslash.chevron.right': 'code',
  'chevron.right': 'chevron_right',
  'chevron.up': 'expand_less',
  creditcard: 'credit_card',
  'doc.on.doc': 'content_copy',
  'doc.text': 'description',
  'dollarsign.circle': 'paid',
  envelope: 'mail',
  'exclamationmark.circle': 'error',
  'exclamationmark.triangle': 'warning',
  hammer: 'build',
  'hand.raised': 'pan_tool',
  'info.circle': 'info',
  'line.3.horizontal.decrease.circle': 'filter_list',
  link: 'link',
  'list.bullet': 'list',
  'list.bullet.rectangle': 'list_alt',
  'list.clipboard': 'assignment',
  location: 'my_location',
  magnifyingglass: 'search',
  map: 'map',
  'mic.fill': 'mic',
  'minus.circle': 'remove_circle',
  person: 'person',
  'person.2.fill': 'group',
  'person.3': 'groups',
  'person.3.fill': 'groups',
  'person.crop.circle': 'account_circle',
  'person.fill': 'person',
  plus: 'add',
  'point.3.connected.trianglepath.dotted': 'hub',
  'quote.opening': 'format_quote',
  safari: 'open_in_browser',
  'slider.horizontal.3': 'tune',
  sparkles: 'auto_awesome',
  'square.3.layers.3d': 'layers',
  'square.and.arrow.up': 'share',
  'square.grid.2x2': 'grid_view',
  'square.on.square': 'content_copy',
  star: 'star',
  'star.fill': 'star',
  tag: 'sell',
  'text.alignleft': 'notes',
  'text.badge.star': 'summarize',
  'text.bubble': 'chat_bubble',
  'text.quote': 'format_quote',
  textformat: 'text_fields',
  'tray.full': 'inventory_2',
  'wifi.slash': 'wifi_off',
  xmark: 'close',
};

export function androidSymbol(name: string): AndroidSymbol {
  return symbols[name] ?? 'article';
}
