// OPAX design tokens. Generated by scripts/build_tokens.mjs from
// docs/design/design-tokens.json: edit the JSON and run the script (npm run
// tokens), never this file. tests/design-tokens.test.ts fails while it is
// stale. palette.ts and tokens.ts re-export it; names, aliases and
// deprecations: docs/design/TOKENS.md.

/** Colour roles, light theme (the one the app renders). */
export const light = {
  /** Page ground. */
  paper: '#FAF9F6',
  /** Cards, sheets, fields, popovers. */
  raised: '#FFFFFF',
  /** Subdued surface: pressed rows, the empty portrait circle, skeleton bars. */
  sunken: '#F1EFE8',
  /** Primary text. */
  ink: '#23271F',
  /** Secondary text, metadata, fine print. */
  inkSoft: '#575C52',
  /** Tertiary text on paper and raised only (4.56 and 4.80:1). */
  inkFaint: '#6F7468',
  /** Text and icons on a navy (or danger) fill. */
  onNavy: '#FFFFFF',
  /** Secondary text on navy. */
  onNavySoft: '#B7C6D9',
  /** Structure and the one primary action per view. */
  navy: '#142A43',
  /** Pressed and hover on navy. */
  navyRaised: '#1D3A5C',
  /** Secondary button fill; the people accent's wash. */
  navyWash: '#E4E6E7',
  /** Rules, chart marks and the masthead rule. */
  bronze: '#A0761B',
  /** Record links, tags, the focus ring on paper. */
  bronzeInk: '#8A5A12',
  /** Tag fill, search highlight. */
  bronzeWash: '#ECE4D3',
  /** Bronze legible on navy: the mark, the focus ring on navy. */
  bronzeBright: '#D9A84A',
  /** The top rule of a section; major content boundaries. */
  dividerDefault: '#B8B4A8',
  /** Between rows, under subheadings, card outlines. */
  dividerSubtle: '#DFDCD2',
  /** Field and segmented-control boundaries only (3.33:1). */
  lineControl: '#8D897B',
  /** Errors and destructive actions. */
  danger: '#A4262C',
  /** A pressed destructive fill (the End call button). */
  dangerPressed: '#86191F',
  /** Money: donations, grants, contracts, pay. */
  moneyInk: '#2B6447',
  /** The money tile and header wash. */
  moneyWash: '#E5EAE5',
  /** Votes: divisions and voting records. */
  votesInk: '#3A4C96',
  /** The votes tile and header wash. */
  votesWash: '#E7E8EC',
  /** Interests: declared interests and registers. */
  interestsInk: '#7B3A63',
  /** The interests tile and header wash. */
  interestsWash: '#EDE6E7',
  /** Bills: bills, stages, exposure drafts; also the machine-written label. */
  billsInk: '#1F5F6B',
  /** The bills tile and header wash. */
  billsWash: '#E4EAE8',
  /** @deprecated Use `dividerSubtle`. */
  line: '#DFDCD2',
  /** @deprecated Use `lineControl`. */
  lineStrong: '#8D897B',
} as const;

export type Role = keyof typeof light;
export type AccentPair = { ink: Role; wash: Role };
export type RolePair = { fg: Role; bg: Role };
export type ClusterColour = { colour: string; ink: string };

/** Colour roles, dark theme: held to the same contrast rules, not rendered (the app is light-only, decision 2). */
export const dark: Record<Role, string> = {
  paper: '#161915',
  raised: '#20241E',
  sunken: '#0E100D',
  ink: '#ECEAE2',
  inkSoft: '#A9AEA2',
  inkFaint: '#8A8F84',
  onNavy: '#0E1A28',
  onNavySoft: '#2A3D53',
  navy: '#9CB9DB',
  navyRaised: '#B9CDE6',
  navyWash: '#25303D',
  bronze: '#A87D2A',
  bronzeInk: '#D9A84A',
  bronzeWash: '#332A1B',
  bronzeBright: '#5E400B',
  dividerDefault: '#4C5047',
  dividerSubtle: '#30342D',
  lineControl: '#7E8378',
  danger: '#F08C8E',
  dangerPressed: '#F6AEB0',
  moneyInk: '#86C6A0',
  moneyWash: '#1D2C24',
  votesInk: '#A9B5F0',
  votesWash: '#232839',
  interestsInk: '#E2A3CA',
  interestsWash: '#33232D',
  billsInk: '#7FC4D0',
  billsWash: '#1B2D30',
  line: '#30342D',
  lineStrong: '#7E8378',
};

/** Increase Contrast: each text role steps one stronger, subtle rules take the default divider, accent inks and bronzeInk reach 7:1. */
export const lightHighContrast: Partial<Record<Role, string>> = {
  inkSoft: '#23271F',
  inkFaint: '#575C52',
  onNavySoft: '#FFFFFF',
  bronzeInk: '#5C4318',
  dividerSubtle: '#B8B4A8',
  moneyInk: '#29553D',
  votesInk: '#374684',
  interestsInk: '#72385C',
  billsInk: '#205158',
  line: '#B8B4A8',
};

export const darkHighContrast: Partial<Record<Role, string>> = {
  inkSoft: '#ECEAE2',
  inkFaint: '#A9AEA2',
  onNavySoft: '#0E1A28',
  bronzeInk: '#EBC57F',
  dividerSubtle: '#4C5047',
  moneyInk: '#A9DDBD',
  votesInk: '#C6CEF8',
  interestsInk: '#EFC3DF',
  billsInk: '#A6DAE3',
  line: '#4C5047',
};

/** Party identity: a dot beside a readable label, never colour alone. */
export const partyColors = {
  labor: '#B02E33',
  liberal: '#1D4F91',
  nationals: '#8F6E00',
  lnp: '#4A90D9',
  greens: '#2E7D32',
  oneNation: '#BF5B15',
  independent: '#3E5B77',
  other: '#7C6690',
} as const;

export type PartyKey = keyof typeof partyColors;

/** A party's colour at 12% over paper, for its own header. */
export const partyWashes: Record<PartyKey, string> = {
  labor: '#F1E1DF',
  liberal: '#DFE5EA',
  nationals: '#EDE8D8',
  lnp: '#E5ECF3',
  greens: '#E2EADE',
  oneNation: '#F3E6DB',
  independent: '#E3E6E7',
  other: '#EBE7EA',
};

export const partyColorsDark: Record<PartyKey, string> = {
  labor: '#E8696D',
  liberal: '#7EA6E6',
  nationals: '#CFA738',
  lnp: '#7DB4EB',
  greens: '#6CC071',
  oneNation: '#EE8F4E',
  independent: '#93AECA',
  other: '#B9A0CF',
};

export const partyWashesDark: Record<PartyKey, string> = {
  labor: '#3A2324',
  liberal: '#1F2A3B',
  nationals: '#332D1A',
  lnp: '#1E2B38',
  greens: '#1F2D20',
  oneNation: '#3A2A1E',
  independent: '#232B33',
  other: '#2D2734',
};

/** A screen's subject and its accent pair. */
export const categories = {
  money: { ink: 'moneyInk', wash: 'moneyWash' },
  votes: { ink: 'votesInk', wash: 'votesWash' },
  interests: { ink: 'interestsInk', wash: 'interestsWash' },
  bills: { ink: 'billsInk', wash: 'billsWash' },
  people: { ink: 'navy', wash: 'navyWash' },
  leads: { ink: 'bronzeInk', wash: 'bronzeWash' },
  /** @deprecated Use `people`. */
  places: { ink: 'navy', wash: 'navyWash' },
} as const satisfies Record<string, AccentPair>;

/** Status labels: always a word; the tone only reinforces it. */
export const statusTones = {
  /** Passed, agreed to, became law, voted for. */
  done: { ink: 'moneyInk', wash: 'moneyWash' },
  /** Before parliament, in committee. */
  active: { ink: 'billsInk', wash: 'billsWash' },
  /** Lapsed, negatived, withdrawn, voted against. */
  ended: { ink: 'inkSoft', wash: 'sunken' },
  /** Exposure draft. */
  draft: { ink: 'bronzeInk', wash: 'bronzeWash' },
} as const satisfies Record<string, AccentPair>;

export const chartRoles = {
  /** The subject series: bars, lines, the one highlighted value. */
  mark: 'bronze',
  /** Tracks, comparison series, gridlines. */
  baseline: 'dividerSubtle',
  /** The second series where a chart compares two (noes against ayes). */
  contrast: 'inkFaint',
} as const satisfies Record<string, Role>;

/** The money map's industry clusters in legend order: a hue and a text-safe ink. Light only. */
export const chartIndustry: readonly (readonly [string, ClusterColour])[] = [
  ['parties', { colour: '#9AA0A8', ink: '#5A616B' }],
  ['unions', { colour: '#E15759', ink: '#A93843' }],
  ['finance', { colour: '#4E79A7', ink: '#365F86' }],
  ['individuals', { colour: '#79706E', ink: '#57504E' }],
  ['property', { colour: '#F28E2B', ink: '#A85A0F' }],
  ['mining & energy', { colour: '#9C755F', ink: '#6E4F3D' }],
  ['hospitality', { colour: '#EDC948', ink: '#7A6414' }],
  ['media & tech', { colour: '#76B7B2', ink: '#3E7A75' }],
  ['health & pharma', { colour: '#59A14F', ink: '#3B7134' }],
  ['gambling', { colour: '#B07AA1', ink: '#7D5273' }],
  ['legal & lobbying', { colour: '#6A51A3', ink: '#4A3775' }],
  ['defence & security', { colour: '#37474F', ink: '#263238' }],
  ['agriculture', { colour: '#6B8E23', ink: '#4A6318' }],
  ['retail', { colour: '#FF9DA7', ink: '#B04A56' }],
  ['tobacco & alcohol', { colour: '#A65628', ink: '#7A3C1B' }],
  ['other', { colour: '#999966', ink: '#6B6B3D' }],
];

/** Registered font names (app/_layout.tsx). */
export const fonts = {
  serif: 'Merriweather',
  serifBold: 'Merriweather-Bold',
  sans: 'PublicSans',
  sansSemiBold: 'PublicSans-SemiBold',
  sansBold: 'PublicSans-Bold',
} as const;

/** Type roles: eleven in use, then the deprecated ones. */
export const typeRoles = {
  /** The page's one title: a person's name, a bill title, a screen name. */
  title: {
    font: 'serif',
    fontSize: 34,
    lineHeight: 42,
    dynamicTypeRamp: 'largeTitle',
    color: 'ink',
  },
  /** The one number a block is about. */
  display: {
    font: 'serifBold',
    fontSize: 34,
    lineHeight: 42,
    dynamicTypeRamp: 'largeTitle',
    color: 'ink',
    tabular: true,
  },
  /** Section heading. */
  heading: {
    font: 'serifBold',
    fontSize: 22,
    lineHeight: 30,
    dynamicTypeRamp: 'title2',
    color: 'ink',
  },
  /** A row title that leads a block: a bill in a list, a division, a report card. */
  subheading: {
    font: 'serifBold',
    fontSize: 18,
    lineHeight: 24,
    dynamicTypeRamp: 'title3',
    color: 'ink',
  },
  /** The words of the record and long reading: speeches, report essays, In short. */
  record: {
    font: 'serif',
    fontSize: 17,
    lineHeight: 29,
    dynamicTypeRamp: 'body',
    color: 'ink',
  },
  /** Interface and OPAX's own sentences. */
  body: {
    font: 'sans',
    fontSize: 17,
    lineHeight: 25,
    dynamicTypeRamp: 'body',
    color: 'ink',
  },
  /** Names in rows, values in key-value lists, inline figures (with tabular). */
  strong: {
    font: 'sansSemiBold',
    fontSize: 17,
    lineHeight: 25,
    dynamicTypeRamp: 'body',
    color: 'ink',
  },
  /** The one meta line under a title: kind · date · place. */
  metadata: {
    font: 'sans',
    fontSize: 15,
    lineHeight: 21,
    dynamicTypeRamp: 'subheadline',
    color: 'inkSoft',
  },
  /** Source lines, saved-copy notices, one short caveat. */
  fine: {
    font: 'sans',
    fontSize: 13,
    lineHeight: 18,
    dynamicTypeRamp: 'footnote',
    color: 'inkSoft',
  },
  /** Tags, status labels, party labels, field labels. */
  label: {
    font: 'sansSemiBold',
    fontSize: 13,
    lineHeight: 18,
    dynamicTypeRamp: 'footnote',
    color: 'inkSoft',
  },
  /** Button, chip and segment labels. */
  control: {
    font: 'sansSemiBold',
    fontSize: 17,
    lineHeight: 22,
    dynamicTypeRamp: 'body',
    color: 'ink',
  },
  /** @deprecated Use `body` (moving changes 16/24 to 17/25). */
  lede: {
    font: 'sans',
    fontSize: 16,
    lineHeight: 24,
    dynamicTypeRamp: 'callout',
    color: 'ink',
  },
  /** @deprecated Use `fine` (moving changes 12/16 to 13/18). */
  caption: {
    font: 'sans',
    fontSize: 12,
    lineHeight: 16,
    dynamicTypeRamp: 'caption1',
    color: 'inkSoft',
  },
  /** @deprecated Use `display` (moving changes Public Sans Bold 28 to Merriweather Bold 34). */
  figure: {
    font: 'sansBold',
    fontSize: 28,
    lineHeight: 34,
    dynamicTypeRamp: 'title1',
    color: 'ink',
    tabular: true,
  },
  /** @deprecated Use `strong` with tabular figures. */
  figureInline: {
    font: 'sansSemiBold',
    fontSize: 17,
    lineHeight: 25,
    dynamicTypeRamp: 'body',
    color: 'ink',
    tabular: true,
  },
  /** @deprecated Use `label` in bronzeInk. */
  tag: {
    font: 'sansSemiBold',
    fontSize: 13,
    lineHeight: 18,
    dynamicTypeRamp: 'footnote',
    color: 'bronzeInk',
  },
  /** @deprecated Use `label`. */
  kicker: {
    font: 'sansSemiBold',
    fontSize: 13,
    lineHeight: 18,
    dynamicTypeRamp: 'footnote',
    color: 'inkSoft',
  },
  /** @deprecated Use `label` (moving changes line height 17 to 18, ink to inkSoft). */
  chip: {
    font: 'sansSemiBold',
    fontSize: 13,
    lineHeight: 17,
    dynamicTypeRamp: 'footnote',
    color: 'ink',
  },
  /** @deprecated Use `control` with tabular figures. */
  countdown: {
    font: 'sansSemiBold',
    fontSize: 17,
    lineHeight: 22,
    dynamicTypeRamp: 'body',
    color: 'ink',
    tabular: true,
  },
  /** @deprecated Use `title` at regular width (`typeRolesRegular.title`). */
  padTitle: {
    font: 'serif',
    fontSize: 42,
    lineHeight: 52,
    dynamicTypeRamp: 'largeTitle',
    color: 'ink',
  },
  /** @deprecated Use `body` (moving changes 19/30 to 17/25). */
  padLede: {
    font: 'sans',
    fontSize: 19,
    lineHeight: 30,
    dynamicTypeRamp: 'body',
    color: 'ink',
  },
} as const;

/** Type steps at regular width (iPad). */
export const typeRolesRegular = {
  title: { fontSize: 42, lineHeight: 52 },
} as const;

/** One vertical rhythm, applied everywhere. */
export const rhythm = {
  /** A line bound to the line above: a date under a title. */
  line: 4,
  /** Inside a row or group: a name to its party line. */
  tight: 8,
  /** Either side of a row hairline (content rows). */
  row: 10,
  /** A section heading to its first block. */
  heading: 12,
  /** Between blocks inside a section. */
  block: 16,
  /** A second list or group inside a section. */
  group: 24,
  /** Between sections; the rule sits at the top of each. */
  section: 36,
  /** Screen edge to content. */
  screen: 20,
} as const;

/** Rhythm steps that grow at regular width (iPad). */
export const rhythmRegular = { section: 56, screen: 32 } as const;

/** @deprecated The web's old phone scale: use `rhythm`. */
export const spacing = {
  /** @deprecated Use `rhythm.line`. */
  s1: 4,
  /** @deprecated Use `rhythm.tight` or `rhythm.line` (moving changes 6 to 8 or 4). */
  s2: 6,
  /** @deprecated Use `rhythm.tight`. */
  s3: 8,
  /** @deprecated Use `rhythm.block`. */
  s4: 16,
  /** @deprecated Use `rhythm.group` (moving changes 26 to 24). */
  s5: 26,
  /** @deprecated Use `rhythm.section`, or `rhythm.screen` at regular width (moving changes 32 to 36). */
  s6: 32,
  /** @deprecated Use `rhythm.section` at regular width (moving changes 52 to 56). */
  s7: 52,
} as const;

/** Shape says what a thing is: press = pill, read = sm, hold = md. */
export const radii = {
  /** Things you read: tags, status labels, text fields, focus outlines, icon tiles. */
  sm: 4,
  /** Things that hold content: cards, sheets, popovers, the Ask composer, the map frame, the error panel. */
  md: 12,
  /** Things you press: buttons, choice and filter chips, the segmented track and thumb, the machine-written label, Follow. */
  pill: 999,
} as const;

export const border = {
  hairline: 1,
  focus: 2,
  accentMarkWidth: 28,
  accentMarkHeight: 2,
  masthead: 3,
} as const;

/** One shadow, for things that float (native sheets and menus draw their own). */
export const elevation = {
  overlay: {
    shadowColor: '#142A43',
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
} as const;

/** Three durations (ms) and one curve (cubic-bezier control points); under Reduce Motion nothing moves. */
export const motion = {
  duration: { quick: 120, standard: 200, gentle: 400 },
  easing: { standard: [0.22, 0.7, 0.3, 1] },
  ambientLoop: 16000,
} as const;

export const size = {
  target: 44,
  targetAndroid: 48,
  controlCompact: 44,
  control: 48,
  controlLarge: 56,
  portraitRow: 44,
  portraitHeader: 72,
  partyDot: 10,
  iconSm: 16,
  iconMd: 20,
  iconLg: 28,
  readable: 700,
} as const;

export const breakpoints = { regular: 700, wide: 1100 } as const;

export const splitPane = { width: 360, min: 300, max: 440 } as const;

/** The pairs the tokens promise: text 4.5:1, nonText 3:1, strong 7:1 under Increase Contrast; forbidden pairs fail AA in light. */
export const contrastRules = {
  text: [
    { fg: 'ink', bg: 'paper' },
    { fg: 'ink', bg: 'raised' },
    { fg: 'ink', bg: 'sunken' },
    { fg: 'ink', bg: 'bronzeWash' },
    { fg: 'ink', bg: 'navyWash' },
    { fg: 'ink', bg: 'moneyWash' },
    { fg: 'ink', bg: 'votesWash' },
    { fg: 'ink', bg: 'interestsWash' },
    { fg: 'ink', bg: 'billsWash' },
    { fg: 'inkSoft', bg: 'paper' },
    { fg: 'inkSoft', bg: 'raised' },
    { fg: 'inkSoft', bg: 'sunken' },
    { fg: 'inkSoft', bg: 'bronzeWash' },
    { fg: 'inkSoft', bg: 'navyWash' },
    { fg: 'inkSoft', bg: 'moneyWash' },
    { fg: 'inkSoft', bg: 'votesWash' },
    { fg: 'inkSoft', bg: 'interestsWash' },
    { fg: 'inkSoft', bg: 'billsWash' },
    { fg: 'inkFaint', bg: 'paper' },
    { fg: 'inkFaint', bg: 'raised' },
    { fg: 'onNavy', bg: 'navy' },
    { fg: 'onNavy', bg: 'navyRaised' },
    { fg: 'onNavy', bg: 'danger' },
    { fg: 'onNavy', bg: 'dangerPressed' },
    { fg: 'onNavySoft', bg: 'navy' },
    { fg: 'navy', bg: 'paper' },
    { fg: 'navy', bg: 'raised' },
    { fg: 'navy', bg: 'sunken' },
    { fg: 'navy', bg: 'navyWash' },
    { fg: 'bronzeInk', bg: 'paper' },
    { fg: 'bronzeInk', bg: 'raised' },
    { fg: 'bronzeInk', bg: 'sunken' },
    { fg: 'bronzeInk', bg: 'bronzeWash' },
    { fg: 'danger', bg: 'paper' },
    { fg: 'danger', bg: 'raised' },
    { fg: 'danger', bg: 'sunken' },
    { fg: 'moneyInk', bg: 'paper' },
    { fg: 'moneyInk', bg: 'raised' },
    { fg: 'moneyInk', bg: 'sunken' },
    { fg: 'moneyInk', bg: 'moneyWash' },
    { fg: 'moneyInk', bg: 'navyWash' },
    { fg: 'votesInk', bg: 'paper' },
    { fg: 'votesInk', bg: 'raised' },
    { fg: 'votesInk', bg: 'sunken' },
    { fg: 'votesInk', bg: 'votesWash' },
    { fg: 'interestsInk', bg: 'paper' },
    { fg: 'interestsInk', bg: 'raised' },
    { fg: 'interestsInk', bg: 'sunken' },
    { fg: 'interestsInk', bg: 'interestsWash' },
    { fg: 'billsInk', bg: 'paper' },
    { fg: 'billsInk', bg: 'raised' },
    { fg: 'billsInk', bg: 'sunken' },
    { fg: 'billsInk', bg: 'billsWash' },
  ],
  nonText: [
    { fg: 'bronze', bg: 'paper' },
    { fg: 'bronze', bg: 'raised' },
    { fg: 'lineControl', bg: 'paper' },
    { fg: 'lineControl', bg: 'raised' },
    { fg: 'lineControl', bg: 'sunken' },
    { fg: 'navy', bg: 'paper' },
    { fg: 'navy', bg: 'raised' },
    { fg: 'navy', bg: 'sunken' },
    { fg: 'danger', bg: 'paper' },
    { fg: 'danger', bg: 'sunken' },
    { fg: 'bronzeBright', bg: 'navy' },
  ],
  strong: [
    { fg: 'bronzeInk', bg: 'bronzeWash' },
    { fg: 'bronzeInk', bg: 'paper' },
    { fg: 'bronzeInk', bg: 'raised' },
    { fg: 'bronzeInk', bg: 'sunken' },
    { fg: 'moneyInk', bg: 'moneyWash' },
    { fg: 'moneyInk', bg: 'paper' },
    { fg: 'moneyInk', bg: 'raised' },
    { fg: 'moneyInk', bg: 'sunken' },
    { fg: 'votesInk', bg: 'votesWash' },
    { fg: 'votesInk', bg: 'paper' },
    { fg: 'votesInk', bg: 'raised' },
    { fg: 'votesInk', bg: 'sunken' },
    { fg: 'interestsInk', bg: 'interestsWash' },
    { fg: 'interestsInk', bg: 'paper' },
    { fg: 'interestsInk', bg: 'raised' },
    { fg: 'interestsInk', bg: 'sunken' },
    { fg: 'billsInk', bg: 'billsWash' },
    { fg: 'billsInk', bg: 'paper' },
    { fg: 'billsInk', bg: 'raised' },
    { fg: 'billsInk', bg: 'sunken' },
  ],
  forbidden: [
    { fg: 'inkFaint', bg: 'sunken' },
    { fg: 'inkFaint', bg: 'bronzeWash' },
    { fg: 'bronze', bg: 'paper' },
  ],
} as const satisfies Record<string, readonly RolePair[]>;
