import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
const folder=mkdtempSync(join(tmpdir(),'opax-community-test-'));
await build({entryPoints:[new URL('../src/community.ts',import.meta.url).pathname,new URL('../src/community-mcp.ts',import.meta.url).pathname,new URL('../src/community-core.ts',import.meta.url).pathname],outdir:folder,bundle:true,platform:'node',format:'esm',packages:'bundle'});
const {communityRoute}=await import(pathToFileURL(join(folder,'community.js')));
const {communityMcp}=await import(pathToFileURL(join(folder,'community-mcp.js')));
const {digest}=await import(pathToFileURL(join(folder,'community-core.js')));
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_community.sql',import.meta.url),'utf8'));const outbox=[];const statement=(sql,args=[])=>({bind(...values){return statement(sql,values)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const result=db.prepare(sql).run(...args);return {success:true,meta:{changes:Number(result.changes)}}}});const env={COMMUNITY_DB:{prepare:statement,async batch(stmts){db.exec('BEGIN');try{const results=[];for(const stmt of stmts)results.push(await stmt.run());db.exec('COMMIT');return results}catch(e){db.exec('ROLLBACK');throw e}}},COMMUNITY_ENABLED:'true',COMMUNITY_ORIGIN:'https://opax.test',COMMUNITY_EMAIL_FROM:'hello@login.opax.test',COMMUNITY_EMAIL:{async send(mail){outbox.push(mail);return {messageId:'test'}}},STRIPE_SUPPORTER_PRICE:'price_support',ASSETS:{async fetch(){return Response.json({entities:[],sources:[]})}}};
const request=(path,method='GET',data,cookie='',headers={})=>new Request('https://opax.test/api/community/'+path,{method,headers:{origin:'https://opax.test',...(data?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...headers},body:data?JSON.stringify(data):undefined});
const call=(...args)=>communityRoute(request(...args),env);
async function login(email='reader@example.com'){assert.equal((await call('auth/request','POST',{email})).status,200);const token=new URL(outbox.at(-1).text.match(/https:\/\/\S+/)[0]).hash.slice(7);const response=await call('auth/consume','POST',{token});assert.equal(response.status,200);return {cookie:response.headers.get('set-cookie').split(';')[0],token,member:db.prepare('SELECT * FROM members WHERE email=?').get(email)}}
return {db,env,outbox,call,request,login}}
test('magic links are single-use, hashed, and issue secure private sessions',async()=>{const f=fixture(),l=await f.login();assert.match(l.cookie,/__Host-opax_session=/);assert.notEqual(f.db.prepare('SELECT token_hash FROM login_links').get().token_hash,l.token);assert.equal((await f.call('auth/consume','POST',{token:l.token})).status,400);const r=await f.call('status','GET',undefined,l.cookie);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).member.email,'reader@example.com');f.db.close()});
test('expired links and tokens cannot sign in',async()=>{const f=fixture();await f.call('auth/request','POST',{email:'a@example.com'});const token=new URL(f.outbox[0].text.match(/https:\/\/\S+/)[0]).hash.slice(7);f.db.exec('UPDATE login_links SET expires_at=0');assert.equal((await f.call('auth/consume','POST',{token})).status,400);assert.equal((await f.call('auth/consume','POST',{token:'x'.repeat(43)})).status,400);f.db.close()});
test('cross-origin account mutations are refused',async()=>{const f=fixture();assert.equal((await f.call('auth/request','POST',{email:'a@example.com'},'',{origin:'https://evil.test'})).status,403);assert.equal(f.outbox.length,0);f.db.close()});
test('email failures invalidate the unused link and do not create accounts',async()=>{const f=fixture();f.env.COMMUNITY_EMAIL.send=async()=>{throw Error('mail failed')};assert.equal((await f.call('auth/request','POST',{email:'a@example.com'})).status,503);assert.equal(f.db.prepare('SELECT count(*) n FROM login_links').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM members').get().n,0);f.db.close()});
test('login rate limits prevent repeated email sends',async()=>{const f=fixture();for(let i=0;i<5;i++)assert.equal((await f.call('auth/request','POST',{email:'a@example.com'})).status,200);assert.equal((await f.call('auth/request','POST',{email:'a@example.com'})).status,429);assert.equal(f.outbox.length,5);f.db.close()});
test('logging out on all devices revokes every session',async()=>{const f=fixture(),a=await f.login(),b=await f.login();assert.equal((await f.call('auth/logout','POST',{everywhere:true},a.cookie)).status,200);assert.equal((await (await f.call('status','GET',undefined,b.cookie)).json()).member,null);f.db.close()});
test('private reading lists stay private and are owner controlled',async()=>{const f=fixture(),a=await f.login(),b=await f.login('second@example.com');const created=await f.call('lists','POST',{title:'Housing records'},a.cookie),{id}=await created.json();assert.equal(created.status,201);assert.equal((await f.call('lists/'+id)).status,404);assert.equal((await f.call('lists/'+id,'GET',undefined,b.cookie)).status,404);assert.equal((await f.call('lists/'+id,'PATCH',{title:'Hijacked',public:true},b.cookie)).status,404);assert.equal((await f.call('lists/'+id+'/items','POST',{title:'Fake',path:'//evil.test/x'},a.cookie)).status,400);assert.equal((await f.call('lists/'+id+'/items','POST',{title:'Speech',path:'/doc/speech-123'},a.cookie)).status,201);await f.call('lists/'+id,'PATCH',{title:'Housing records',public:true},a.cookie);assert.equal((await f.call('lists/'+id)).status,200);await f.call('lists/'+id,'DELETE',undefined,a.cookie);assert.equal(f.db.prepare('SELECT count(*) n FROM reading_list_items').get().n,0);f.db.close()});
test('public profiles do not expose email addresses or billing IDs',async()=>{const f=fixture(),a=await f.login();const payload=await (await f.call('members/'+a.member.id)).json();assert.equal(payload.member.email,undefined);assert.equal(payload.member.stripe_customer,undefined);f.db.close()});
test('discussions require a signed-in profile and support report/removal',async()=>{const f=fixture(),a=await f.login(),b=await f.login('b@example.com');const data={title:'A useful question',body:'What does this sourced record show?',source_path:'/doc/speech-123'};assert.equal((await f.call('threads','POST',data)).status,401);assert.equal((await f.call('threads','POST',data,a.cookie)).status,400);await f.call('profile','PATCH',{name:'A reader',bio:''},a.cookie);const {id}=await (await f.call('threads','POST',data,a.cookie)).json();assert.equal((await f.call('threads/'+id,'DELETE',undefined,b.cookie)).status,404);assert.equal((await f.call('reports','POST',{target:id,reason:'Please review this'},b.cookie)).status,200);assert.equal((await f.call('reports','GET',undefined,b.cookie)).status,403);await f.call('threads/'+id,'DELETE',undefined,a.cookie);assert.equal((await f.call('threads/'+id)).status,404);f.db.close()});
test('disabled accounts cannot retain sessions',async()=>{const f=fixture(),a=await f.login();f.db.exec('UPDATE members SET disabled=1');assert.equal((await f.call('lists','GET',undefined,a.cookie)).status,401);f.db.close()});
test('MCP is gated by active support and revocable hashed tokens',async()=>{const f=fixture(),a=await f.login();assert.equal((await f.call('keys','POST',{name:'Reader tool'},a.cookie)).status,403);const t=Math.floor(Date.now()/1000);f.db.prepare('INSERT INTO supporter_subscriptions VALUES (?,?,?,?,?,?,?,?,?)').run('sub_1',a.member.id,'cus_1','active','price_support',t+86400,0,Date.now(),0);const created=await f.call('keys','POST',{name:'Reader tool'},a.cookie),{id,token}=await created.json();assert.equal(created.status,201);const keyList=await (await f.call('keys','GET',undefined,a.cookie)).text();assert.ok(!keyList.includes(token));assert.equal(f.db.prepare('SELECT token_hash FROM mcp_keys').get().token_hash,await digest(token));const send=()=>communityMcp(new Request('https://opax.test/mcp',{method:'POST',headers:{authorization:'Bearer '+token,accept:'application/json, text/event-stream','content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}}})}),f.env,async()=>Response.json({results:[]}));let r=await send();assert.equal(r.status,200);assert.ok((await r.json()).result.capabilities.tools);f.db.exec("UPDATE supporter_subscriptions SET status='canceled'");assert.equal((await send()).status,403);f.db.exec("UPDATE supporter_subscriptions SET status='active'");await f.call('keys/'+id,'DELETE',undefined,a.cookie);assert.equal((await send()).status,401);f.db.close()});
test.after(()=>rmSync(folder,{recursive:true,force:true}));

async function stripeFixture(t,f,respond){
 f.env.STRIPE_SECRET_KEY='sk_test_fixture';f.env.STRIPE_WEBHOOK_SECRET='whsec_fixture';
 t.mock.method(globalThis,'fetch',async(input,init)=>{const url=new URL(typeof input==='string'?input:input.url);assert.equal(url.hostname,'api.stripe.com');return respond(url,init)});
}
test('Stripe outages do not take free accounts offline',async t=>{const f=fixture(),a=await f.login();await stripeFixture(t,f,()=>Response.json({error:{type:'invalid_request_error',message:'Unavailable'}},{status:400}));const response=await f.call('status','GET',undefined,a.cookie);assert.equal(response.status,200);const data=await response.json();assert.equal(data.member.id,a.member.id);assert.equal(data.contribution,null);f.db.close()});
test('webhooks reject unsigned events and reconcile duplicates and stale events with Stripe',async t=>{
 const f=fixture(),a=await f.login();f.db.prepare('UPDATE members SET stripe_customer=? WHERE id=?').run('cus_fixture',a.member.id);
 let active=true,calls=0;await stripeFixture(t,f,url=>{assert.equal(url.pathname,'/v1/subscriptions');calls++;return Response.json({object:'list',has_more:false,data:[{id:'sub_fixture',status:active?'active':'canceled',cancel_at_period_end:false,items:{data:[{price:{id:'price_support'},current_period_end:Math.floor(Date.now()/1000)+86400}]}}]})});
 const {createHmac}=await import('node:crypto');const timestamp=Math.floor(Date.now()/1000);
 const send=async(created,signature=true)=>{const raw=JSON.stringify({id:'evt_fixture',object:'event',type:'customer.subscription.updated',created,data:{object:{id:'sub_fixture',customer:'cus_fixture',status:'active'}}});const sig=createHmac('sha256','whsec_fixture').update(timestamp+'.'+raw).digest('hex');return communityRoute(new Request('https://opax.test/api/community/billing/webhook',{method:'POST',headers:{'content-type':'application/json',...(signature?{'stripe-signature':`t=${timestamp},v1=${sig}`}:{})},body:raw}),f.env)};
 assert.equal((await send(timestamp,false)).status,400);assert.equal(calls,0);
 assert.equal((await send(timestamp)).status,200);assert.equal((await send(timestamp)).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM supporter_subscriptions').get().n,1);
 active=false;assert.equal((await send(timestamp-100)).status,200);assert.equal(f.db.prepare('SELECT status FROM supporter_subscriptions').get().status,'canceled');f.db.close();
});
test('checkout retries reuse the same idempotency key and open session',async t=>{
 const f=fixture(),a=await f.login();f.db.prepare('UPDATE members SET stripe_customer=? WHERE id=?').run('cus_fixture',a.member.id);const creates=[];let fail=true;
 await stripeFixture(t,f,(url,init)=>{
  if(url.pathname==='/v1/subscriptions')return Response.json({object:'list',data:[],has_more:false});
  if(url.pathname==='/v1/prices/price_support')return Response.json({id:'price_support',active:true,currency:'aud',recurring:{interval:'month'}});
  if(url.pathname==='/v1/checkout/sessions/cs_fixture')return Response.json({id:'cs_fixture',status:'open',url:'https://checkout.stripe.com/c/pay/fixture'});
  assert.equal(url.pathname,'/v1/checkout/sessions');creates.push({key:new Headers(init.headers).get('idempotency-key'),body:String(init.body)});
  if(fail){fail=false;return Response.json({error:{type:'invalid_request_error',message:'Interrupted checkout'}},{status:400})}
  return Response.json({id:'cs_fixture',url:'https://checkout.stripe.com/c/pay/fixture'});
 });
 assert.equal((await f.call('billing/checkout','POST',{},a.cookie)).status,503);
 assert.equal((await f.call('billing/checkout','POST',{},a.cookie)).status,200);
 assert.equal((await f.call('billing/checkout','POST',{},a.cookie)).status,200);
 assert.equal(creates.length,2);assert.ok(creates[0].key?.startsWith('opax-checkout-'));assert.deepEqual(creates[0],creates[1]);assert.equal(f.db.prepare('SELECT count(*) n FROM supporter_checkouts').get().n,1);f.db.close();
});

test('MCP tools return usable record citations and bound oversized responses',async()=>{
 const f=fixture(),a=await f.login(),t=Math.floor(Date.now()/1000);
 f.db.prepare('INSERT INTO supporter_subscriptions VALUES (?,?,?,?,?,?,?,?,?)').run('sub_tools',a.member.id,'cus_tools','active','price_support',t+86400,0,Date.now(),0);
 const {token}=await (await f.call('keys','POST',{name:'Tool checks'},a.cookie)).json();
 let read=async path=>Response.json(path.startsWith('/api/search-all')?{results:[{slug:'speech-931754',title:'Housing'},{href:'/subject/supplier/example',title:'Supplier'}]}:{slug:'speech-931754',text:'Source text'});
 const send=async(method,params={})=>{const r=await communityMcp(new Request('https://opax.test/mcp',{method:'POST',headers:{authorization:'Bearer '+token,accept:'application/json, text/event-stream','content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:2,method,params})}),f.env,path=>read(path));assert.equal(r.status,200);return (await r.json()).result};
 const listed=await send('tools/list');assert.deepEqual(listed.tools.map(x=>x.name).sort(),['corpus_coverage','find_connections','read_record','search_records']);
 const search=await send('tools/call',{name:'search_records',arguments:{query:'housing'}});assert.equal(search.isError,false);const results=JSON.parse(search.content[0].text).results;assert.equal(results[0].opax_url,'https://opax.test/doc/speech-931754');assert.equal(results[1].opax_url,'https://opax.test/subject/supplier/example');
 const record=await send('tools/call',{name:'read_record',arguments:{slug:'speech-931754'}});assert.equal(JSON.parse(record.content[0].text).opax_url,'https://opax.test/doc/speech-931754');
 const invalid=await send('tools/call',{name:'read_record',arguments:{slug:'../../account'}});assert.equal(invalid.isError,true);
 let cancelled=false;read=async()=>new Response(new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(100000))},cancel(){cancelled=true}}));
 const large=await send('tools/call',{name:'read_record',arguments:{slug:'speech-931754'}});assert.equal(large.isError,true);assert.equal(cancelled,true);assert.equal(JSON.parse(large.content[0].text).url,'https://opax.test/doc/speech-931754');f.db.close();
});
