import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

// /support?record=<path> names the record a report is about and pre-fills the
// public GitHub issue. Only a public record route's own shape may reach either.
const app = readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
const pick = (name) => app.match(new RegExp(`function ${name}\\([^)]*\\) \\{[\\s\\S]*?\\n\\}`))[0];
const constant = (name) => app.match(new RegExp(`^const ${name} = .*$`, 'm'))[0];
const { supportRecord, supportRecordHref, supportIssueUrl } = runInNewContext(
  `const SITE_ORIGIN = "https://opax.com.au"; ${constant('SUPPORT_ISSUES')} ${constant('SUPPORT_DIRS')} ${constant('SUPPORT_SECTIONS')}
   ${pick('supportRecord')} ${pick('supportRecordHref')} ${pick('supportIssueUrl')} ({ supportRecord, supportRecordHref, supportIssueUrl })`,
  { URLSearchParams, String, encodeURIComponent, decodeURIComponent },
);
// The record value as /support receives it: the outer query decoded once, as renderSupport does.
const received = (query) => new URLSearchParams(query).get('record');

// OPAX's own sign-in, session and deletion tokens (src/community-core.ts),
// generated by the real function: 32 random bytes as base64url, 43 characters.
const core = readFileSync(new URL('../src/community-core.ts', import.meta.url), 'utf8');
const randomToken = runInNewContext(`(${core.match(/export const randomToken = (\(\) => \{[^\n]*\})/)[1]})`, { crypto, btoa, Uint8Array, String });

test('a report keeps a public record path in the shapes OPAX links to', () => {
  for (const [given, kept] of [
    ['/doc/speech-123456', '/doc/speech-123456'],
    ['/doc/division-2024-09-01-house-3', '/doc/division-2024-09-01-house-3'],
    ['/bill/au-federal-r5113', '/bill/au-federal-r5113'],
    ['/reports/gambling', '/reports/gambling'],
    ['/reports/gambling/s/3', '/reports/gambling/s/3'],
    ['/subject/topic/housing', '/subject/topic/housing'],
    ['/subject/person/tony-abbott', '/subject/person/tony-abbott'],
    ['/subject/person/Tony%20Abbott', '/subject/person/Tony Abbott'],
    ['/subject/person/Tony Abbott', '/subject/person/Tony Abbott'],
    ['/subject/person/Kim%20O%E2%80%99Keeffe', '/subject/person/Kim O’Keeffe'],
    ['/subject/person/K.J.%20Maher', '/subject/person/K.J. Maher'],
    ['/subject/donor/PricewaterhouseCoopers', '/subject/donor/PricewaterhouseCoopers'],
    ['/subject/donor/Capital%20%5Bb%5D%20Pty%20Ltd', '/subject/donor/Capital [b] Pty Ltd'],
    ['/subject/supplier/s-f7cb920c42fc7e570eeb', '/subject/supplier/s-f7cb920c42fc7e570eeb'],
    ['/subject/agency/a-aaa167b0097858604254', '/subject/agency/a-aaa167b0097858604254'],
    ['/money/grants/qld/recipient/abn%3A18374210672', '/money/grants/qld/recipient/abn:18374210672'],
    ['/money/grants/federal/recipient/name%3Agreek%20orthodox%20archdiocese', '/money/grants/federal/recipient/name:greek orthodox archdiocese'],
    ['/money/grants', '/money/grants'], ['/money/receipts', '/money/receipts'], ['/discover', '/discover'], ['/bills/', '/bills'],
    // The query and fragment never survive, whatever they hold.
    ['/money/grants?jur=federal&program=GO3141', '/money/grants'],
    ['/doc/abc#private-note', '/doc/abc'],
    ['/doc/abc?email=person%40example.invalid&token=synthetic-token', '/doc/abc'],
  ]) assert.equal(supportRecord(given), kept, given);
  assert.equal(supportRecordHref('/subject/person/Kim O’Keeffe'), '/subject/person/Kim%20O%E2%80%99Keeffe');
});

test('anything else gets the general form: other routes, emails, keys, escapes and off-site paths', () => {
  for (const bad of [
    '/search?q=private-question', '/ask?q=my medical history', '/community?token=synthetic-token&email=person%40example.invalid',
    '/community', '/api/community/status', '/mcp', '/ingest/e', '/og/doc/abc.png', '/chat', '/privacy',
    '/subject/person/jane.citizen@example.invalid', '/doc/person%40example.invalid', '/subject/person/jane%EF%BC%A0example.invalid',
    '/doc/opax_q8Zr3kLmN0pXyT5vWb2cD7eFgH1jK4sA9uQ6iO3wE', '/doc/q8Zr3kLmN0pXyT5vWb2cD7eF', '/doc/0123456789abcdef0123456789abcdef',
    '/doc/a=b', '/doc/x_y', '/doc/Speech-1', '/doc/1-speech', '/doc/speech--1', '/subject/person/12345678', '/bill/' + 'a'.repeat(65),
    '/doc/abc%3Ftoken%3Dsynthetic-token', '/doc/abc%23private-note', '/doc/%2520', '/doc/%E0%A4%A', '/doc/abc%00',
    '/subject/person/' + 'Word '.repeat(41).trim(),
    '//evil.example', '/\\evil.example', '/doc/%5Cevil.example', 'https://evil.example/doc', 'javascript:alert(1)', '/doc/<b>', '',
    null, undefined, 'doc/abc',
  ]) assert.equal(supportRecord(bad), '', String(bad));
});

test('dot segments and encoded slashes never reach another route, literal or encoded', () => {
  for (const bad of [
    '/doc/..', '/doc/.', '/doc/a/..', '/doc/../community', '/doc/../api/community/status', '/doc/../../../../community',
    '/subject/person/../../community', '/doc/%2e%2e/community', '/doc/%2E%2E', '/doc/.%2e', '/doc/%2F..%2Fcommunity',
    '/doc/%2Fcommunity', '/subject/campaigner/T%2FA%20Union', '/doc/．．/community',
  ]) assert.equal(supportRecord(bad), '', bad);
  // The reviewer's forms through the outer query: once encoded, and twice.
  for (const query of ['record=%2Fdoc%2F..%2Fcommunity', 'record=%2Fdoc%2F%252e%252e%2Fcommunity', 'record=%252Fdoc%252F..%252Fcommunity']) {
    assert.equal(supportRecord(received(query)), '', query);
  }
});

test('OPAX tokens never pass, in any record position', () => {
  // The reviewer's synthetic, inactive token: digitless, so the old rule let it through.
  const synthetic = 'AbCdEfGhIj-KlMnOpQrSt-UvWxYzAbCd-EfGhIjKlMk';
  assert.equal(supportRecord(received('record=%2Fdoc%2FAbCdEfGhIj-KlMnOpQrSt-UvWxYzAbCd-EfGhIjKlMk')), '');
  const positions = (t) => [
    `/doc/${t}`, `/bill/${t}`, `/reports/${t}`, `/subject/topic/${t}`,
    ...['person', 'party', 'donor', 'supplier', 'agency', 'campaigner', 'electorate'].map((dir) => `/subject/${dir}/${t}`),
    `/money/grants/federal/recipient/name:${t}`, `/money/grants/qld/recipient/person:${t}`, `/doc/opax_${t}`,
  ];
  for (const path of positions(synthetic)) assert.equal(supportRecord(path), '', path);
  let tried = 0;
  const accepted = [];
  for (let i = 0; i < 10_000; i++) {
    const token = randomToken();
    assert.equal(token.length, 43);
    for (const path of positions(token)) {
      tried++;
      if (supportRecord(path) || supportRecord(received(`record=${encodeURIComponent(path)}`))) accepted.push(path);
    }
  }
  assert.deepEqual(accepted, [], `${accepted.length} of ${tried} token paths accepted`);
});

test('the GitHub issue is pre-filled with the record, or left general without one', () => {
  const withRecord = new URL(supportIssueUrl('/subject/person/Tony Abbott'));
  assert.equal(withRecord.origin + withRecord.pathname, 'https://github.com/jaketracey/opax/issues/new');
  assert.equal(withRecord.searchParams.get('title'), 'Correction: /subject/person/Tony Abbott');
  assert.match(withRecord.searchParams.get('body'), /^Record: https:\/\/opax\.com\.au\/subject\/person\/Tony%20Abbott\n\nWhat is wrong:/);
  for (const raw of ['/doc/abc?email=person%40example.invalid&token=synthetic-token#note', '/community?token=synthetic-token',
    '/doc/AbCdEfGhIj-KlMnOpQrSt-UvWxYzAbCd-EfGhIjKlMk', '/doc/../community']) {
    const url = supportIssueUrl(supportRecord(raw));
    assert.doesNotMatch(decodeURIComponent(url), /example\.invalid|synthetic-token|note|AbCdEf|community/, raw);
  }
  const general = new URL(supportIssueUrl(''));
  assert.equal(general.searchParams.get('title'), 'Correction');
  assert.match(general.searchParams.get('body'), /^Record or page:/);
});

test('every record path in the search catalog is kept, or the refusals are counted', (t) => {
  // The catalog is build output (npm run build:search); the deploy workflow builds it before tests.
  const root = new URL('../public/search-catalog/', import.meta.url);
  const versions = existsSync(root) ? readdirSync(root, { withFileTypes: true }).filter((d) => d.isDirectory()) : [];
  if (!versions.length) { t.skip('no search catalog built'); return; }
  const paths = new Set();
  for (const dir of versions) {
    for (const file of readdirSync(new URL(`${dir.name}/`, root)).filter((f) => f.startsWith('records-'))) {
      const text = readFileSync(new URL(`${dir.name}/${file}`, root), 'utf8');
      for (const m of text.matchAll(/"(\/(?:doc|bill|bills|reports|subject|money|connections|declared|discover|explore)(?:\/[^"?#\s]*)?)"/g)) paths.add(m[1]);
    }
  }
  const refused = [...paths].filter((p) => !supportRecord(p));
  t.diagnostic(`${refused.length} of ${paths.size} catalog record paths refused: ${refused.slice(0, 5).join(' | ')}`);
  // Names holding an encoded slash ("T%2FA") are refused by rule; nothing else should be.
  assert.deepEqual(refused.filter((p) => !/%2F/i.test(p)), []);
});

test('/support is a shell route with metadata and a sitemap entry', () => {
  const html = readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
  const worker = readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8');
  assert.match(html, /<section id="panel-support" class="panel" hidden/);
  assert.match(app, /const PANELS = \[[^\]]*"support"/);
  assert.match(worker, /support: \{\n\s+title: 'Support · OPAX'/);
  assert.match(worker, /'privacy', 'support'\]\) add\(`\/\$\{page\}`\)/);
  for (const page of ['index.html', 'home.html', 'community.html']) {
    assert.match(readFileSync(new URL(`../public/${page}`, import.meta.url), 'utf8'), /href="\/support"/, page);
  }
});
