// Verify the native policy generated by the CNG plugins.
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import config from '../app.config';
const plist = JSON.parse(
  execFileSync(
    '/usr/bin/plutil',
    ['-convert', 'json', '-o', '-', 'ios/OPAX/Info.plist'],
    { encoding: 'utf8' },
  ),
);
assert(
  !plist.NSMicrophoneUsageDescription,
  'Microphone permission is deferred',
);
if (config.ios?.infoPlist?.NSAppTransportSecurity)
  assert.deepEqual(
    plist.NSAppTransportSecurity,
    config.ios?.infoPlist?.NSAppTransportSecurity,
  );
else assert(!plist.NSAppTransportSecurity, 'Production has no ATS exception');
assert.deepEqual(plist.UIApplicationSceneManifest, {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: 'EXExpoAppSceneDelegate',
      },
    ],
  },
});
const delegate = readFileSync('ios/OPAX/AppDelegate.swift', 'utf8');
assert(
  delegate.includes('ExpoAppDelegate, ExpoReactNativeFactoryProvider') &&
    delegate.includes('reactNativeFactory = factory') &&
    !/window = UIWindow|factory\.startReactNative/.test(delegate),
  'Expo scene delegate owns the window and React Native startup',
);
console.log(`PASS CNG native policy: ${config.extra?.variant}`);
