// Verify the native policy generated by the CNG plugins.
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import config from '../app.config';
const plist = JSON.parse(
  execFileSync(
    '/usr/bin/plutil',
    ['-convert', 'json', '-o', '-', 'ios/OPAX/Info.plist'],
    { encoding: 'utf8' },
  ),
);
assert.equal(
  plist.NSLocationWhenInUseUsageDescription,
  'OPAX uses your location once, on your iPhone, to suggest your electorate. It is not sent anywhere.',
);
assert(
  !plist.NSLocationAlwaysUsageDescription &&
    !plist.NSLocationAlwaysAndWhenInUseUsageDescription,
);
assert(!plist.UIBackgroundModes?.includes('location'));
assert(
  !plist.NSMicrophoneUsageDescription,
  'Microphone permission is deferred',
);
if (config.extra?.variant === 'production') {
  assert(
    !plist.OPAXVoiceFixturePort,
    'Production has no native voice fixture configuration',
  );
  assert(
    readFileSync('ios/Podfile', 'utf8').includes(
      "use_expo_modules! :exclude => ['opax-voice']",
    ),
    'Production excludes both voice pods',
  );
} else if (config.extra?.variant === 'e2e')
  assert.equal(
    plist.OPAXVoiceFixturePort,
    Number(process.env.OPAX_FIXTURE_PORT ?? 8910),
  );
if (config.ios?.infoPlist?.NSAppTransportSecurity)
  assert.deepEqual(
    plist.NSAppTransportSecurity,
    config.ios?.infoPlist?.NSAppTransportSecurity,
  );
else assert(!plist.NSAppTransportSecurity, 'Production has no ATS exception');
assert.deepEqual(plist.UIApplicationSceneManifest, {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: 'EXExpoAppSceneDelegate',
      },
    ],
  },
});
const delegate = readFileSync('ios/OPAX/AppDelegate.swift', 'utf8');
assert(
  delegate.includes('ExpoAppDelegate, ExpoReactNativeFactoryProvider') &&
    delegate.includes('reactNativeFactory = factory') &&
    !/window = UIWindow|factory\.startReactNative/.test(delegate),
  'Expo scene delegate owns the window and React Native startup',
);
console.log(`PASS CNG native policy: ${config.extra?.variant}`);
