// Verify the native policy generated by the CNG plugins.
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import config from '../app.config';
import { policy } from '../plugins/voiceProduction';
const productionVoice = config.extra?.productionVoiceEnabled === true;
const plist = JSON.parse(
  execFileSync(
    '/usr/bin/plutil',
    ['-convert', 'json', '-o', '-', 'ios/OPAX/Info.plist'],
    { encoding: 'utf8' },
  ),
);
assert.equal(
  plist.NSLocationWhenInUseUsageDescription,
  'OPAX uses your location once, on your iPhone, to suggest your electorate. It is not sent anywhere.',
);
assert.equal(
  plist.NSMotionUsageDescription,
  'OPAX doesn\'t use motion or fitness data. iOS requires this note because the location library behind "Use my location" includes motion features that OPAX never turns on.',
);
assert(
  !plist.NSLocationAlwaysUsageDescription &&
    !plist.NSLocationAlwaysAndWhenInUseUsageDescription,
);
assert(!plist.UIBackgroundModes?.includes('location'));
assert.equal(
  plist.NSMicrophoneUsageDescription,
  productionVoice ? policy.microphonePurpose : undefined,
);
if (config.extra?.variant === 'production') {
  assert(
    !plist.OPAXVoiceFixturePort,
    'Production has no native voice fixture configuration',
  );
  assert(
    readFileSync('ios/Podfile', 'utf8').includes(
      "use_expo_modules! :exclude => ['opax-voice']",
    ) === !productionVoice,
    'Production voice pods follow the build-time switch',
  );
  const lock = readFileSync('ios/Podfile.lock', 'utf8');
  for (const name of ['OpaxVoice', 'OpaxVoiceCore'])
    assert.equal(
      new RegExp(`^  - ${name} \\(`, 'm').test(lock),
      productionVoice,
      `${name} linking`,
    );
  if (productionVoice) {
    assert.equal(plist.OPAXProductionVoiceEnabled, true);
    assert.equal(plist.OPAXVoiceConsentDefault, false);
    assert.deepEqual(plist.OPAXVoiceAllowedRoutes, policy.routes);
    for (const name of ['OpaxVoice', 'OpaxVoiceCore']) {
      const settings = readFileSync(
        `ios/Pods/Target Support Files/${name}/${name}.release.xcconfig`,
        'utf8',
      );
      assert(
        settings.includes('OPAX_VOICE_PRODUCTION'),
        `${name} production compile gate`,
      );
      assert(
        !/OPAX_VOICE_E2E|\bDEBUG\b/.test(settings),
        `${name} has no synthetic compile gate`,
      );
    }
  }
} else if (config.extra?.variant === 'e2e')
  assert.equal(
    plist.OPAXVoiceFixturePort,
    Number(process.env.OPAX_FIXTURE_PORT ?? 8910),
  );
if (config.ios?.infoPlist?.NSAppTransportSecurity)
  assert.deepEqual(
    plist.NSAppTransportSecurity,
    config.ios?.infoPlist?.NSAppTransportSecurity,
  );
else assert(!plist.NSAppTransportSecurity, 'Production has no ATS exception');
assert.deepEqual(plist.UIApplicationSceneManifest, {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: 'EXExpoAppSceneDelegate',
      },
    ],
  },
});
const delegate = readFileSync('ios/OPAX/AppDelegate.swift', 'utf8');
assert(
  delegate.includes('ExpoAppDelegate, ExpoReactNativeFactoryProvider') &&
    delegate.includes('reactNativeFactory = factory') &&
    !/window = UIWindow|factory\.startReactNative/.test(delegate),
  'Expo scene delegate owns the window and React Native startup',
);
assert.equal(
  delegate.includes('OpaxSearchGeometryProbe.start()'),
  config.extra?.variant === 'e2e',
  'Native Search geometry instrumentation is fixture-only',
);
console.log(`PASS CNG native policy: ${config.extra?.variant}`);
