#!/usr/bin/env node
/**
 * Build the design tokens for the web and the app from one source:
 * docs/design/design-tokens.json.
 *
 *   node scripts/build_tokens.mjs                 # write every target present
 *   node scripts/build_tokens.mjs --check         # exit 1 if a target is stale
 *   node scripts/build_tokens.mjs --only web      # web | app | docs
 *
 * Targets (each is skipped when its package is not in this checkout, so the
 * script runs on main, which has no mobile/, and on ios/app, whose portal/
 * predates the token region):
 *   web   portal/public/tokens.css, and the same rules inlined into the
 *         marked region at the top of portal/public/style.css, so a page
 *         needs no second request
 *   app   mobile/src/design/tokens.generated.ts, re-exported by palette.ts
 *         and tokens.ts
 *   docs  the generated tables in docs/design/TOKENS.md
 *
 * The source keeps old names as aliases for one release; see `deprecated` in
 * the JSON. The token tests on both sides run `--check`.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
export const SOURCE = join(ROOT, 'docs', 'design', 'design-tokens.json')
const TOKENS_CSS = join(ROOT, 'portal', 'public', 'tokens.css')
const STYLE_CSS = join(ROOT, 'portal', 'public', 'style.css')
const APP_TS = join(ROOT, 'mobile', 'src', 'design', 'tokens.generated.ts')
const DOCS = join(ROOT, 'docs', 'design', 'TOKENS.md')

export const STYLE_BEGIN = '/* tokens:begin'
export const STYLE_END = '/* tokens:end */'
const DOCS_BEGIN = '<!-- tokens:begin (generated by scripts/build_tokens.mjs) -->'
const DOCS_END = '<!-- tokens:end -->'

const THEMES = ['light', 'dark', 'lightHighContrast', 'darkHighContrast']
const REF = /^\{([A-Za-z]+)\}$/
const HEX = /^#[0-9A-F]{6}$/

const own = (object) => Object.entries(object).filter(([key]) => !key.startsWith('$'))
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const rem = (px) => `${+(px / 16).toFixed(4)}rem`
const ratio = (lineHeight, size) => +(lineHeight / size).toFixed(3)
const firstSentence = (text = '') => (text.match(/^.*?\.(?=\s|$)/)?.[0] ?? text).trim()

export function loadSource(file = SOURCE) {
  return JSON.parse(readFileSync(file, 'utf8'))
}

/** Colour roles in source order, with their web and app names. */
export function colourRoles(source) {
  const roles = []
  for (const [group, entries] of own(source.color))
    for (const [name, token] of own(entries)) {
      if (!('$value' in token)) throw new Error(`color.${group}.${name} has no $value`)
      if (!('dark' in token)) throw new Error(`color.${group}.${name} has no dark value`)
      roles.push({
        name,
        group,
        token,
        web: token.web?.name ?? `--${kebab(name)}`,
        app: !token.app?.omit,
        description: token.$description ?? '',
      })
    }
  const names = new Set()
  for (const role of roles) {
    if (names.has(role.name)) throw new Error(`duplicate colour role ${role.name}`)
    names.add(role.name)
  }
  return roles
}

/**
 * Every role's value in each theme. A reference resolves in the theme's base
 * (light or dark): Increase Contrast steps inkFaint to the base inkSoft, not to
 * the stepped-up one. A hex Increase Contrast value needs a dark counterpart.
 */
export function palettes(source) {
  const roles = colourRoles(source)
  const byName = new Map(roles.map((role) => [role.name, role]))
  const raw = {
    light: (role) => role.token.$value,
    dark: (role) => role.token.dark,
    lightHighContrast: (role) => role.token.highContrast,
    darkHighContrast: (role) => {
      const { highContrast, darkHighContrast } = role.token
      if (darkHighContrast !== undefined) return darkHighContrast
      if (highContrast !== undefined && !REF.test(highContrast))
        throw new Error(`${role.name}: a hex highContrast value needs darkHighContrast`)
      return highContrast
    },
  }
  const base = { light: 'light', dark: 'dark', lightHighContrast: 'light', darkHighContrast: 'dark' }
  const resolve = (value, theme, seen = []) => {
    const ref = REF.exec(value)
    if (!ref) return value
    const target = byName.get(ref[1])
    if (!target) throw new Error(`unknown colour reference ${value}`)
    if (seen.includes(ref[1])) throw new Error(`circular reference ${[...seen, ref[1]].join(' > ')}`)
    return resolve(raw[theme](target), theme, [...seen, ref[1]])
  }
  const out = {}
  for (const theme of THEMES) {
    out[theme] = {}
    for (const role of roles) {
      const value = raw[theme](role)
      if (value === undefined) continue
      out[theme][role.name] = resolve(value, base[theme])
    }
  }
  for (const theme of ['light', 'dark'])
    for (const role of roles)
      if (role.app && !HEX.test(out[theme][role.name]))
        throw new Error(`${role.name} (${theme}) must be an opaque #RRGGBB colour: ${out[theme][role.name]}`)
  return out
}

/** Party dots and washes per theme, in source order. */
export function parties(source) {
  const list = own(source.party).map(([key, party]) => ({ key, ...party }))
  for (const party of list)
    for (const value of [party.dot, party.wash, party.dark?.dot, party.dark?.wash])
      if (!HEX.test(value ?? '')) throw new Error(`party.${party.key} needs opaque dot and wash in both themes`)
  return list
}

/** The contrast promises, expanded to one row per pair. */
export function contrastPairs(source) {
  const roles = new Set(colourRoles(source).map((role) => role.name))
  const rows = {}
  for (const [kind, list] of own(source.contrast)) {
    rows[kind] = list.flatMap(({ fg, on }) =>
      on.map((bg) => {
        for (const name of [fg, bg]) if (!roles.has(name)) throw new Error(`contrast.${kind}: unknown role ${name}`)
        return { fg, bg }
      }),
    )
  }
  return rows
}

function typeRole(role, platform) {
  const web = platform === 'web' ? role.web ?? {} : {}
  return {
    family: role.family,
    weight: web.weight ?? role.weight,
    size: web.size ?? role.size,
    lineHeight: web.lineHeight ?? role.lineHeight,
    ramp: role.ramp,
    color: role.color,
    tabular: role.tabular === true,
  }
}

function deprecationNote(entry) {
  const use = entry.alias ?? entry.use
  const change = entry.change && entry.change !== 'none' ? `; moving changes ${entry.change}` : ''
  return `deprecated: use ${use}${change}`
}

/** A TypeScript @deprecated line: names in backticks, the change in brackets. */
function deprecatedDoc(entry) {
  const use = (entry.alias ?? entry.use).replace(/\b(?:rhythm|radii|typeRolesRegular|accents|light)\.\w+|^\w+$|^\w+(?= )/g, (name) => `\`${name}\``)
  const change = entry.change && entry.change !== 'none' ? ` (moving changes ${entry.change})` : ''
  return `@deprecated Use ${use}${change}.`
}

// --- web ---------------------------------------------------------------------

function webDeclarations(source) {
  const roles = colourRoles(source)
  const themes = palettes(source)
  const groups = []
  const push = (title, lines) => groups.push({ title, lines })
  const decl = (name, value, note) => `  ${name}: ${value};${note ? ` /* ${note} */` : ''}`

  for (const group of [...new Set(roles.map((role) => role.group))])
    push(
      `colour: ${group}`,
      roles
        .filter((role) => role.group === group)
        .map((role) =>
          decl(role.web, role.token.web?.value ?? themes.light[role.name], firstSentence(role.description)),
        ),
    )
  const webName = new Map(roles.map((role) => [role.name, role.web]))
  const ref = (name) => `var(${webName.get(name)})`
  push(
    'status tones',
    own(source.status).flatMap(([tone, { ink, wash }]) => [
      decl(`--status-${tone}-ink`, ref(ink)),
      decl(`--status-${tone}-wash`, ref(wash)),
    ]),
  )
  push('chart', [
    ...['mark', 'baseline', 'contrast'].map((key) =>
      decl(`--chart-${key}`, ref(source.chart[key].role), firstSentence(source.chart[key].$description)),
    ),
    ...own(source.chart.industry).flatMap(([cluster, { colour, ink }]) => [
      decl(`--chart-industry-${slug(cluster)}`, colour),
      decl(`--chart-industry-${slug(cluster)}-ink`, ink),
    ]),
  ])
  push(
    'party: a dot beside the name; the wash only on a party header',
    parties(source).flatMap((party) => [
      decl(`--party-${party.web}`, party.dot),
      decl(`--party-${party.web}-wash`, party.wash),
    ]),
  )

  const families = { serif: source.font.serif.web, sans: source.font.sans.web }
  const font = (role) => {
    const size = typeof role.size === 'number' ? rem(role.size) : role.size
    const lineHeight = role.lineHeight > 3 ? ratio(role.lineHeight, role.size) : role.lineHeight
    return `${role.weight} ${size}/${lineHeight} var(--${role.family})`
  }
  push('type: eleven roles; serif speaks for the record, sans for OPAX', [
    decl('--serif', families.serif),
    decl('--sans', families.sans),
    ...own(source.type).map(([name, role]) =>
      decl(`--type-${kebab(name)}`, font(typeRole(role, 'web')), firstSentence(role.$description)),
    ),
  ])
  const space = own(source.space)
  push(
    'space: one rhythm',
    space.map(([name, token]) =>
      decl(`--space-${kebab(name)}`, token.web?.value ?? rem(token.$value), firstSentence(token.$description)),
    ),
  )
  push(
    'radius: press = pill, read = sm, hold = md',
    own(source.radius).map(([name, token]) =>
      decl(`--radius-${kebab(name)}`, typeof token.$value === 'number' ? `${token.$value}px` : token.$value),
    ),
  )
  push(
    'border',
    own(source.border).map(([name, token]) => decl(`--border-${kebab(name)}`, `${token.$value}px`)),
  )
  const shadow = source.elevation.overlay
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(shadow.color.slice(i, i + 2), 16))
  push('elevation: one shadow, for things that float', [
    decl('--shadow-overlay', `${shadow.x} ${shadow.y}px ${shadow.blur}px rgba(${r}, ${g}, ${b}, ${shadow.alpha})`),
  ])
  push('motion: three durations, one curve', [
    ...own(source.motion.duration).map(([name, token]) => decl(`--duration-${kebab(name)}`, `${token.$value}ms`)),
    decl('--ease-standard', `cubic-bezier(${source.motion.easing.standard.$value.join(', ')})`),
    decl('--ambient-loop', `${source.motion.ambientLoop.$value / 1000}s`),
  ])
  push(
    'size',
    own(source.size).map(([name, token]) => {
      const value = token.web ?? token.$value
      return decl(`--size-${kebab(name)}`, typeof value === 'number' ? `${value}px` : value)
    }),
  )
  push('layout', [
    decl('--layout-column-wide', `${source.layout.columnWide.$value}px`),
    decl('--layout-column-web-max', `${source.layout.columnWebMax.$value}px`),
  ])

  const deprecated = own(source.deprecated.web)
  const declared = new Set(groups.flatMap(({ lines }) => lines.map((line) => line.trim().split(':')[0])))
  for (const [name, entry] of deprecated) {
    if (declared.has(name)) throw new Error(`${name} is both a token and a deprecated name`)
    if (entry.alias && !declared.has(entry.alias)) throw new Error(`${name} aliases unknown ${entry.alias}`)
  }
  push(
    'deprecated: kept for one release (docs/design/TOKENS.md)',
    deprecated.map(([name, entry]) => decl(name, entry.alias ? `var(${entry.alias})` : entry.value, deprecationNote(entry))),
  )

  const regular = space
    .filter(([, token]) => token.regular !== undefined && !token.web)
    .map(([name, token]) => decl(`--space-${kebab(name)}`, rem(token.regular)))
  const compact = deprecated.filter(([, entry]) => entry.compact).map(([name, entry]) => decl(name, entry.compact))
  const highContrast = source.themes.web.prefersContrast
    ? roles
        .filter((role) => role.token.highContrast !== undefined && !role.token.web?.value)
        .map((role) => decl(role.web, themes.lightHighContrast[role.name]))
    : []
  return { groups, regular, compact, highContrast }
}

export function buildCss(source) {
  const { groups, regular, compact, highContrast } = webDeclarations(source)
  const blocks = [
    [':root {', `  color-scheme: ${source.themes.web.colorScheme};`, ...groups.flatMap(({ title, lines }) => ['', `  /* ${title} */`, ...lines]), '}'].join('\n'),
  ]
  if (regular.length) blocks.push(`@media (min-width: ${source.layout.regular.$value + 1}px) {\n  :root {\n${regular.map((line) => `  ${line}`).join('\n')}\n  }\n}`)
  if (compact.length) blocks.push(`@media (max-width: ${source.layout.regular.$value}px) {\n  :root {\n${compact.map((line) => `  ${line}`).join('\n')}\n  }\n}`)
  if (highContrast.length) blocks.push(`@media (prefers-contrast: more) {\n  :root {\n${highContrast.map((line) => `  ${line}`).join('\n')}\n  }\n}`)
  return blocks.join('\n') + '\n'
}

export function tokensCss(source) {
  return (
    '/* OPAX design tokens. Generated by scripts/build_tokens.mjs from\n' +
    '   docs/design/design-tokens.json: edit the JSON and run the script, never\n' +
    '   this file. style.css carries the same rules inline. Names, aliases and\n' +
    '   deprecations: docs/design/TOKENS.md. */\n' +
    buildCss(source)
  )
}

/** style.css with its marked token region replaced by the generated rules. */
export function styleWithTokens(style, source) {
  const begin = style.indexOf(STYLE_BEGIN)
  const end = style.indexOf(STYLE_END)
  if (begin < 0 || end < begin) throw new Error('style.css has no tokens:begin / tokens:end region')
  const region =
    `${STYLE_BEGIN}: generated by scripts/build_tokens.mjs from\n` +
    '   docs/design/design-tokens.json, the same rules as tokens.css, inlined so a\n' +
    '   page needs no second request. Edit the JSON, never this region. */\n' +
    buildCss(source)
  return style.slice(0, begin) + region + style.slice(end)
}

// --- app ---------------------------------------------------------------------

const WIDTH = 80
const quote = (text) => (text.includes("'") && !text.includes('"') ? JSON.stringify(text) : `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`)
const keyName = (key) => (/^[A-Za-z_$][\w$]*$/.test(key) ? key : quote(key))

/**
 * A small printer that writes what Prettier would (single quotes, trailing
 * commas, 80 columns): a value stays on one line when it fits; arrays of two or
 * more objects or tuples always break; a property with a comment breaks its
 * object. `{ $doc, value }` attaches a JSDoc comment to a property.
 */
function print(value, indent, prefix, suffix) {
  if (value === null || typeof value !== 'object') return `${typeof value === 'string' ? quote(value) : value}`
  const pad = ' '.repeat(indent + 2)
  if (Array.isArray(value)) {
    const items = value.map((item) => print(item, indent + 2, '', ','))
    const inline = `[${items.join(', ')}]`
    const forced = value.length > 1 && value.every((item) => item && typeof item === 'object' && (Array.isArray(item) ? item.length > 1 : Object.keys(item).length > 0))
    if (!forced && !inline.includes('\n') && indent + prefix.length + inline.length + suffix.length <= WIDTH) return inline
    return `[\n${value.map((item) => `${pad}${print(item, indent + 2, '', ',')},`).join('\n')}\n${' '.repeat(indent)}]`
  }
  const entries = Object.entries(value)
  if (!entries.length) return '{}'
  const documented = entries.some(([, item]) => item && typeof item === 'object' && '$doc' in item)
  const parts = entries.map(([key, item]) => {
    const doc = item && typeof item === 'object' && '$doc' in item ? item.$doc : null
    const inner = doc !== null ? item.value : item
    const head = `${keyName(key)}: `
    return { doc, line: head + print(inner, indent + 2, head, ',') }
  })
  const inline = `{ ${parts.map((part) => part.line).join(', ')} }`
  if (!documented && !inline.includes('\n') && indent + prefix.length + inline.length + suffix.length <= WIDTH) return inline
  const lines = parts.map(({ doc, line }) => (doc ? `${pad}/** ${doc} */\n` : '') + `${pad}${line},`)
  return `{\n${lines.join('\n')}\n${' '.repeat(indent)}}`
}
const exportConst = (name, value, { type = '', tail = '', doc = '' } = {}) => {
  const head = `export const ${name}${type ? `: ${type}` : ''} = `
  return `${doc ? `/** ${doc} */\n` : ''}${head}${print(value, 0, head, `${tail};`)}${tail};\n`
}
const documented = (value, doc) => (doc ? { $doc: doc, value } : value)

export function buildTs(source) {
  const roles = colourRoles(source).filter((role) => role.app)
  const themes = palettes(source)
  const deprecatedRoles = own(source.deprecated.app.roles)
  for (const [name, entry] of deprecatedRoles)
    if (!roles.some((role) => role.name === entry.alias)) throw new Error(`light.${name} aliases unknown role ${entry.alias}`)
  const forTheme = (theme, withDocs) => {
    const out = {}
    for (const role of roles) if (themes[theme][role.name] !== undefined) out[role.name] = documented(themes[theme][role.name], withDocs ? firstSentence(role.description) : '')
    for (const [name, entry] of deprecatedRoles)
      if (themes[theme][entry.alias] !== undefined) out[name] = documented(themes[theme][entry.alias], withDocs ? `@deprecated Use \`${entry.alias}\`.` : '')
    return out
  }
  const partyList = parties(source)
  const fromParties = (pick) => Object.fromEntries(partyList.map((party) => [party.key, pick(party)]))
  const faces = own(source.font.appFaces)
  const faceKey = (family, weight) => {
    const key = source.font[family].app[weight]
    if (!key) throw new Error(`no app face for ${family} ${weight}`)
    return key
  }
  const appType = (role) => ({
    font: faceKey(role.family, String(role.weight)),
    fontSize: role.size,
    lineHeight: role.lineHeight,
    dynamicTypeRamp: role.ramp,
    color: role.color,
    ...(role.tabular ? { tabular: true } : {}),
  })
  const typeRoles = {}
  for (const [name, role] of own(source.type)) typeRoles[name] = documented(appType(typeRole(role, 'app')), firstSentence(role.$description))
  for (const [name, entry] of own(source.deprecated.app.textStyles)) {
    const role = entry.alias ? { ...source.type[entry.alias], $description: '' } : entry
    typeRoles[name] = documented(appType(typeRole(role, 'app')), deprecatedDoc(entry))
  }
  const typeRegular = Object.fromEntries(own(source.type).filter(([, role]) => role.regular).map(([name, role]) => [name, { fontSize: role.regular.size, lineHeight: role.regular.lineHeight }]))
  const space = own(source.space)
  const shadow = source.elevation.overlay
  const categories = Object.fromEntries(own(source.category).map(([name, pair]) => [name, { ink: pair.ink, wash: pair.wash }]))
  for (const [name, entry] of own(source.deprecated.app.accents)) categories[name] = documented(categories[entry.alias], `@deprecated Use \`${entry.alias}\`.`)
  const pairs = contrastPairs(source)
  const spaceStep = (alias) => {
    const token = source.space[alias.replace(/^rhythm\./, '')]
    if (!token) throw new Error(`unknown rhythm step ${alias}`)
    return token.$value
  }

  const parts = [
    '// OPAX design tokens. Generated by scripts/build_tokens.mjs from\n' +
      '// docs/design/design-tokens.json: edit the JSON and run the script (npm run\n' +
      '// tokens), never this file. tests/design-tokens.test.ts fails while it is\n' +
      '// stale. palette.ts and tokens.ts re-export it; names, aliases and\n' +
      '// deprecations: docs/design/TOKENS.md.\n',
    exportConst('light', forTheme('light', true), { tail: ' as const', doc: 'Colour roles, light theme (the one the app renders).' }),
    'export type Role = keyof typeof light;\nexport type AccentPair = { ink: Role; wash: Role };\nexport type RolePair = { fg: Role; bg: Role };\nexport type ClusterColour = { colour: string; ink: string };\n',
    exportConst('dark', forTheme('dark', false), { type: 'Record<Role, string>', doc: 'Colour roles, dark theme: held to the same contrast rules, not rendered (the app is light-only, decision 2).' }),
    exportConst('lightHighContrast', forTheme('lightHighContrast', false), { type: 'Partial<Record<Role, string>>', doc: 'Increase Contrast: each text role steps one stronger, subtle rules take the default divider, accent inks and bronzeInk reach 7:1.' }),
    exportConst('darkHighContrast', forTheme('darkHighContrast', false), { type: 'Partial<Record<Role, string>>' }),
    exportConst('partyColors', fromParties((party) => party.dot), { tail: ' as const', doc: 'Party identity: a dot beside a readable label, never colour alone.' }),
    'export type PartyKey = keyof typeof partyColors;\n',
    exportConst('partyWashes', fromParties((party) => party.wash), { type: 'Record<PartyKey, string>', doc: "A party's colour at 12% over paper, for its own header." }),
    exportConst('partyColorsDark', fromParties((party) => party.dark.dot), { type: 'Record<PartyKey, string>' }),
    exportConst('partyWashesDark', fromParties((party) => party.dark.wash), { type: 'Record<PartyKey, string>' }),
    exportConst('categories', categories, { tail: ' as const satisfies Record<string, AccentPair>', doc: "A screen's subject and its accent pair." }),
    exportConst('statusTones', Object.fromEntries(own(source.status).map(([tone, pair]) => [tone, documented({ ink: pair.ink, wash: pair.wash }, firstSentence(pair.$description))])), { tail: ' as const satisfies Record<string, AccentPair>', doc: 'Status labels: always a word; the tone only reinforces it.' }),
    exportConst('chartRoles', Object.fromEntries(['mark', 'baseline', 'contrast'].map((key) => [key, documented(source.chart[key].role, firstSentence(source.chart[key].$description))])), { tail: ' as const satisfies Record<string, Role>' }),
    exportConst('chartIndustry', own(source.chart.industry).map(([cluster, { colour, ink }]) => [cluster, { colour, ink }]), { type: 'readonly (readonly [string, ClusterColour])[]', doc: "The money map's industry clusters in legend order: a hue and a text-safe ink. Light only." }),
    exportConst('fonts', Object.fromEntries(faces), { tail: ' as const', doc: 'Registered font names (app/_layout.tsx).' }),
    exportConst('typeRoles', typeRoles, { tail: ' as const', doc: 'Type roles: eleven in use, then the deprecated ones.' }),
    exportConst('typeRolesRegular', typeRegular, { tail: ' as const', doc: 'Type steps at regular width (iPad).' }),
    exportConst('rhythm', Object.fromEntries(space.map(([name, token]) => [name, documented(token.$value, firstSentence(token.$description))])), { tail: ' as const', doc: 'One vertical rhythm, applied everywhere.' }),
    exportConst('rhythmRegular', Object.fromEntries(space.filter(([, token]) => token.regular !== undefined).map(([name, token]) => [name, token.regular])), { tail: ' as const', doc: 'Rhythm steps that grow at regular width (iPad).' }),
    exportConst('spacing', Object.fromEntries(own(source.deprecated.app.spacing).map(([name, entry]) => [name, documented(entry.alias ? spaceStep(entry.alias) : entry.value, deprecatedDoc(entry))])), { tail: ' as const', doc: "@deprecated The web's old phone scale: use `rhythm`." }),
    exportConst('radii', Object.fromEntries(own(source.radius).filter(([, token]) => !token.app?.omit).map(([name, token]) => [name, documented(token.$value, firstSentence(token.$description))])), { tail: ' as const', doc: 'Shape says what a thing is: press = pill, read = sm, hold = md.' }),
    exportConst('border', Object.fromEntries(own(source.border).map(([name, token]) => [name, token.$value])), { tail: ' as const' }),
    exportConst('elevation', { overlay: { shadowColor: shadow.color, shadowOpacity: shadow.alpha, shadowRadius: shadow.blur / 2, shadowOffset: { width: shadow.x, height: shadow.y }, elevation: shadow.y } }, { tail: ' as const', doc: 'One shadow, for things that float (native sheets and menus draw their own).' }),
    exportConst('motion', { duration: Object.fromEntries(own(source.motion.duration).map(([name, token]) => [name, token.$value])), easing: { standard: source.motion.easing.standard.$value }, ambientLoop: source.motion.ambientLoop.$value }, { tail: ' as const', doc: 'Three durations (ms) and one curve (cubic-bezier control points); under Reduce Motion nothing moves.' }),
    exportConst('size', Object.fromEntries(own(source.size).flatMap(([name, token]) => [[name, token.$value], ...(token.android ? [[`${name}Android`, token.android]] : [])])), { tail: ' as const' }),
    exportConst('breakpoints', { regular: source.layout.regular.$value, wide: source.layout.wide.$value }, { tail: ' as const' }),
    exportConst('splitPane', { width: source.layout.splitPane.$value, min: source.layout.splitPane.min, max: source.layout.splitPane.max }, { tail: ' as const' }),
    exportConst('contrastRules', pairs, { tail: ' as const satisfies Record<string, readonly RolePair[]>', doc: 'The pairs the tokens promise: text 4.5:1, nonText 3:1, strong 7:1 under Increase Contrast; forbidden pairs fail AA in light.' }),
  ]
  return parts.join('\n')
}

// --- docs --------------------------------------------------------------------

export function buildDocsTables(source) {
  const roles = colourRoles(source)
  const themes = palettes(source)
  const code = (text) => `\`${text}\``
  const lines = []
  lines.push('### Colour roles', '', '| Role | Web | App | Light | Dark | Increase Contrast | Use |', '|---|---|---|---|---|---|---|')
  for (const role of roles) {
    const value = role.token.web?.value ? `${themes.light[role.name]} (web ${code(role.token.web.value)})` : themes.light[role.name]
    const ic = themes.lightHighContrast[role.name] ? `${themes.lightHighContrast[role.name]} / ${themes.darkHighContrast[role.name]}` : ''
    lines.push(`| ${role.group} | ${code(role.web)} | ${role.app ? code(role.name) : 'none'} | ${value} | ${themes.dark[role.name]} | ${ic} | ${firstSentence(role.description)} |`)
  }
  const counts = {
    roles: roles.length,
    groups: new Set(roles.map((role) => role.group)).size,
    type: own(source.type).length,
    sizes: new Set(own(source.type).map(([, role]) => role.size)).size,
    radii: own(source.radius).length,
  }
  lines.push(
    '',
    `${counts.roles} colour roles in ${counts.groups} groups; ${own(source.category).length} categories, ${own(source.status).length} status tones, ${own(source.chart.industry).length} industry hues, ${own(source.party).length} parties (dot + wash); ${counts.type} type roles over ${counts.sizes} sizes; ${own(source.space).length} rhythm steps; ${counts.radii} radii (${own(source.radius).map(([name]) => name).join(', ')}); ${own(source.motion.duration).length} durations and 1 curve; 1 shadow.`,
  )
  const table = (title, rows) => {
    lines.push('', `### ${title}`, '', '| Old name | Kind | Use instead | Moving changes |', '|---|---|---|---|')
    for (const [name, entry] of rows)
      lines.push(`| ${code(name)} | ${entry.alias ? 'alias (same value)' : `legacy value ${code(String(entry.value ?? ''))}`} | ${code(entry.alias ?? entry.use)} | ${entry.alias || !entry.change || entry.change === 'none' ? 'nothing' : entry.change} |`)
  }
  table('Deprecated web names', own(source.deprecated.web))
  const app = source.deprecated.app
  table('Deprecated app names', [
    ...own(app.roles).map(([name, entry]) => [`light.${name}`, { alias: `light.${entry.alias}` }]),
    ...own(app.accents).map(([name, entry]) => [`accents.${name}`, { alias: `accents.${entry.alias}` }]),
    ['radius', app.radius],
    ...own(app.spacing).map(([name, entry]) => [`spacing.${name}`, entry]),
    ...own(app.textStyles).map(([name, entry]) => [`textStyles.${name}`, entry.alias ? { alias: `textStyles.${entry.alias}` } : { ...entry, value: `${entry.size}/${entry.lineHeight}` }]),
  ])
  return lines.join('\n')
}

export function docsWithTables(docs, source) {
  const begin = docs.indexOf(DOCS_BEGIN)
  const end = docs.indexOf(DOCS_END)
  if (begin < 0 || end < begin) throw new Error('TOKENS.md has no tokens:begin / tokens:end region')
  return `${docs.slice(0, begin)}${DOCS_BEGIN}\n\n${buildDocsTables(source)}\n\n${docs.slice(end)}`
}

// --- targets -----------------------------------------------------------------

export function targets(source = loadSource()) {
  const list = []
  // The web target starts once style.css carries the token region (main);
  // a branch with an older portal/ (ios/app before it merges main) skips it.
  if (existsSync(STYLE_CSS) && readFileSync(STYLE_CSS, 'utf8').includes(STYLE_BEGIN)) {
    list.push({ kind: 'web', file: TOKENS_CSS, content: () => tokensCss(source) })
    list.push({ kind: 'web', file: STYLE_CSS, content: () => styleWithTokens(readFileSync(STYLE_CSS, 'utf8'), source) })
  }
  if (existsSync(dirname(APP_TS))) list.push({ kind: 'app', file: APP_TS, content: () => buildTs(source) })
  if (existsSync(DOCS)) list.push({ kind: 'docs', file: DOCS, content: () => docsWithTables(readFileSync(DOCS, 'utf8'), source) })
  return list
}

/** Stale targets, as paths relative to the repo root. */
export function staleTargets(kinds) {
  return targets()
    .filter((target) => !kinds || kinds.includes(target.kind))
    .filter((target) => !existsSync(target.file) || readFileSync(target.file, 'utf8') !== target.content())
    .map((target) => relative(ROOT, target.file))
}

function main(argv) {
  const check = argv.includes('--check')
  const only = argv.includes('--only') ? argv[argv.indexOf('--only') + 1]?.split(',') : null
  if (only?.some((kind) => !['web', 'app', 'docs'].includes(kind))) throw new Error('--only takes web, app or docs')
  const chosen = targets().filter((target) => !only || only.includes(target.kind))
  if (!chosen.length) throw new Error(`no ${only?.join('/') ?? ''} target in this checkout`)
  let stale = 0
  for (const target of chosen) {
    const next = target.content()
    const current = existsSync(target.file) ? readFileSync(target.file, 'utf8') : null
    if (current === next) continue
    stale++
    if (check) console.error(`stale: ${relative(ROOT, target.file)}`)
    else {
      writeFileSync(target.file, next)
      console.log(`wrote ${relative(ROOT, target.file)}`)
    }
  }
  if (check && stale) {
    console.error('Design tokens are stale: run `node scripts/build_tokens.mjs` and commit the result.')
    process.exit(1)
  }
  if (check) console.log(`design tokens up to date (${chosen.length} files)`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main(process.argv.slice(2))
