import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {sponsorFor} from '../portal/src/seo-content.ts';
const pub = new URL('../portal/public/',import.meta.url);
export function buildSpaShell({check=false}={}) {
  const index=readFileSync(new URL('index.html',pub),'utf8');
  const content=index.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)?.[1];
  if (!content) throw Error('SPA main missing');
  // This script runs before app.js; all existing panel IDs and listeners survive.
  // A policy page's server copy (data-panel-copy, panelPrerender in seo-content.ts)
  // repeats its panel's section ids; the copy gives them up once the panel is back.
  const generated='// Generated by scripts/build_spa_shell.mjs from index.html.\n'+
    '(()=>{const main=document.getElementById("main");if(main?.hasAttribute("data-server-rendered")){const answer=main.querySelector("#prerender");main.innerHTML='+JSON.stringify(content)+';if(answer){if(answer.hasAttribute("data-panel-copy"))for(const el of answer.querySelectorAll("[id]"))el.removeAttribute("id");main.prepend(answer);}}})();\n';
  const target=new URL('spa-shell.js',pub);
  const old=(()=>{try{return readFileSync(target,'utf8')}catch{return ''}})();
  if (check && old!==generated) throw Error('spa-shell.js stale; run stamp');
  if (!check && old!==generated) writeFileSync(target,generated);
  const sponsored={};
  const people=JSON.parse(readFileSync(new URL('parliamentarians.json',pub),'utf8')).people;
  const rows=JSON.parse(readFileSync(new URL('bills/index.json',pub),'utf8')).bills;
  for(const row of rows){
    const b=JSON.parse(readFileSync(new URL(`bills/${row.key}.json`,pub),'utf8'));
    const sponsor=sponsorFor(b,people);
    const id=b.sponsor_person_id || sponsor?.pid || sponsor?.name;
    if(id)(sponsored[id]??=[]).push(b.key);
  }
  const links=JSON.stringify({sponsored})+'\n';
  const linksFile=new URL('seo-links.json',pub);
  const prior=(()=>{try{return readFileSync(linksFile,'utf8')}catch{return ''}})();
  if(check && prior!==links) throw Error('seo-links.json stale; run stamp');
  if(!check && prior!==links) writeFileSync(linksFile,links);
}
if(process.argv[1]===fileURLToPath(import.meta.url))buildSpaShell({check:process.argv.includes('--check')});
