#!/usr/bin/env node
/**
 * Content-hash stamp the portal's un-hashed entry assets, so public/_headers
 * can serve them immutable.
 *
 * portal/public/index.html references /app.js?v=<hash> and /style.css?v=<hash>.
 * This rewrites both stamps from the bytes on disk. A new release is then a new
 * URL, and a returning visitor picks it up on the first request instead of
 * sitting on a year-old cache entry.
 * Also syncs the homepage header, mobile drawer and footer from index.html.
 *
 *   node scripts/stamp_assets.mjs           # stamp (what `npm run deploy` runs)
 *   node scripts/stamp_assets.mjs --check   # exit 1 if the stamps are stale
 *   node scripts/stamp_assets.mjs --fonts   # re-pull the self-hosted webfonts
 *
 * WHY IT MUST RUN: `wrangler deploy` on its own ships an unstamped index.html
 * against immutable Cache-Control. Deploy with `npm run deploy`, never by hand.
 *
 * Most modules app.js import()s at runtime (money-map.js, statemap.js, voice.js,
 * ...) are fetched by a path written into app.js, with a hand-bumped ?v= where it
 * matters; _headers gives them max-age=300 + a day of stale-while-revalidate.
 * The modules in MODULE_STAMPS are the exception: they load the who-is-who files
 * themselves (portraits, the roster), so a browser must never run a cached copy of
 * an old one. Each gets its content hash written into its importer here, before
 * the importer itself is hashed, so a changed module is a new URL all the way up
 * (docs/PHOTOS.md, "Caches"). `--check` fails when one of those stamps is stale.
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSpaShell } from './build_spa_shell.mjs'
import { buildMethods } from './build_methods.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PUBLIC = join(ROOT, 'portal', 'public')
const INDEX = join(PUBLIC, 'index.html')

/** Assets referenced from index.html with a ?v= stamp. */
const STAMPED = ['app.js', 'spa-shell.js', 'spa-entry.js', 'style.css', 'analytics.js', 'gtm.js', 'events.js', 'navigation.js', 'quick-search.js', 'voice.css', 'ui-controls.css', 'ui-source.css', 'ui-source.js', 'labels.js']

const hashOf = (file) =>
  createHash('sha256').update(readFileSync(join(PUBLIC, file))).digest('hex').slice(0, 10)

// --- webfonts ---------------------------------------------------------------
// Self-hosting is what removed ~2.3s of render blocking (a serial round trip to
// fonts.googleapis.com just to learn the fonts.gstatic.com URLs) and two origins
// from the CSP. Google still owns the upstream files, so this refreshes them
// from the same CSS2 request the old <link> made, using a modern Chrome UA so
// the API answers with woff2.
const FONT_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;0,900;1,400' +
  '&family=Public+Sans:wght@400..700&display=swap'
const FONT_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
// Cyrillic is dropped on purpose: it is ~90 KB of repo for codepoints Hansard
// does not use, and the serif/sans fallbacks cover it if it ever appears.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'vietnamese'])
const FILE_STEM = { Merriweather: 'merriweather', 'Public Sans': 'public-sans' }
// The faces preloaded from index.html: the first serif and the first sans.
const PRELOAD = ['merriweather-normal-latin.woff2', 'public-sans-normal-latin.woff2']

const FONTS_BEGIN = '<!-- fonts:begin (generated by scripts/stamp_assets.mjs --fonts) -->'
const FONTS_END = '<!-- fonts:end -->'

async function refreshFonts() {
  const css = await (await fetch(FONT_CSS_URL, { headers: { 'user-agent': FONT_UA } })).text()
  const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)]
  if (!blocks.length) throw new Error('no @font-face blocks in the Google Fonts response')

  const dir = join(PUBLIC, 'fonts')
  mkdirSync(dir, { recursive: true })
  const faces = []
  const seen = new Set()
  for (const [, subset, decl] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue
    const family = /font-family:\s*'([^']+)'/.exec(decl)[1]
    const style = /font-style:\s*(\w+)/.exec(decl)[1]
    const src = /url\((https:\/\/[^)]+)\)/.exec(decl)[1]
    const range = /unicode-range:\s*([^;]+);/.exec(decl)[1].trim().replace(/,\s+/g, ',')
    const file = `${FILE_STEM[family]}-${style}-${subset}.woff2`
    if (seen.has(file)) continue
    seen.add(file)
    // Variable fonts: one file serves the whole axis. Merriweather's is
    // 400-900, Public Sans's 400-700; style.css uses 400/600/700.
    const weight = family === 'Merriweather' ? '400 900' : '400 700'
    const bytes = Buffer.from(await (await fetch(src, { headers: { 'user-agent': FONT_UA } })).arrayBuffer())
    writeFileSync(join(dir, file), bytes)
    faces.push({ family, style, weight, file, range, size: bytes.length })
  }
  for (const stale of readdirSync(dir)) {
    if (stale.endsWith('.woff2') && !seen.has(stale)) unlinkSync(join(dir, stale))
  }
  for (const want of PRELOAD) {
    if (!seen.has(want)) throw new Error(`preloaded face ${want} is no longer served by Google`)
  }

  const block = [
    FONTS_BEGIN,
    ...PRELOAD.map(
      (f) => `<link rel="preload" as="font" type="font/woff2" crossorigin href="/fonts/${f}">`,
    ),
    '<style>',
    ...faces.map(
      ({ family, style, weight, file, range }) =>
        `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
        `font-display:swap;src:url(/fonts/${file}) format('woff2');unicode-range:${range}}`,
    ),
    '</style>',
    FONTS_END,
  ].join('\n')

  const html = readFileSync(INDEX, 'utf8')
  const start = html.indexOf(FONTS_BEGIN)
  const end = html.indexOf(FONTS_END)
  if (start < 0 || end < 0) throw new Error('fonts:begin/fonts:end markers missing from index.html')
  writeFileSync(INDEX, html.slice(0, start) + block + html.slice(end + FONTS_END.length))
  for (const f of faces) console.log(`  font  ${f.file.padEnd(38)} ${String(f.size).padStart(7)} bytes`)
}

// --- stamping ---------------------------------------------------------------

/** [importer, module]: modules whose changes must invalidate their importer.
 *  An importer that is itself stamped into another comes first, so its own
 *  new stamp is in the hash its importer takes (labels.js reaches app.js
 *  directly and through electorates.js, and home.js through home-data.js).
 *  agencies.js and suppliers.js import each other: stamp the agencies → suppliers
 *  edge only, then app.js. Keep the reverse edge hand-versioned to avoid a hash cycle. */
export const MODULE_STAMPS = [
  ['growth-modules.js', 'donor-entity.js'], ['growth-modules.js', 'labels.js'], ['growth-modules.js', 'sponsor-person.js'],
  ['supplier-growth.js', 'growth-modules.js'], ['supplier-growth.js', 'labels.js'],

  ['canonical-urls.js', 'person-paths.js'],
  ['ballot.js', 'canonical-urls.js'],
  ['electorates.js', 'canonical-urls.js'],
  ['evidence.js', 'canonical-urls.js'],
  ['grants.js', 'canonical-urls.js'],
  ['grant-recipient.js', 'canonical-urls.js'],
  ['home-data.js', 'canonical-urls.js'],
  ['home.js', 'canonical-urls.js'],
  ['ledger.js', 'canonical-urls.js'],
  ['money-journeys.js', 'canonical-urls.js'],
  ['quiz.js', 'canonical-urls.js'],
  ['suppliers.js', 'canonical-urls.js'], ['suppliers.js', 'labels.js'], ['suppliers.js', 'supplier-growth.js'], ['agencies.js', 'suppliers.js'],
  ['timemachine.js', 'canonical-urls.js'], ['timemachine.js', 'labels.js'],
  // The money map's bundle names its chunks by content, so an importer holding
  // an old money-map.js would ask for chunks the build has removed.
  ['map-page.js', 'money-map.js'], ['agencies.js', 'money-map.js'], ['suppliers.js', 'money-map.js'],
  ['thenvsnow.js', 'wombat.js'], ['thenvsnow.js', 'labels.js'], ['grant-recipient.js', 'grants.js'],
  ['electorates.js', 'labels.js'], ['home-data.js', 'labels.js'],
  ['app.js', 'canonical-urls.js'], ['app.js', 'growth-modules.js'], ['app.js', 'suppliers.js'],
  ['app.js', 'labels.js'], ['app.js', 'electorates.js'], ['app.js', 'division-markdown.js'], ['app.js', 'quiz.js'], ['app.js', 'timemachine.js'],
  ['app.js', 'money-map.js'], ['app.js', 'explain.js'], ['app.js', 'grant-recipient.js'],
  // The Explore tools and the loaders, restyled on tokens in pass 4G.
  ['app.js', 'ballot.js'], ['app.js', 'grants.js'], ['app.js', 'ledger.js'], ['app.js', 'matrix.js'], ['app.js', 'wordsdollars.js'],
  ['app.js', 'thenvsnow.js'], ['app.js', 'statemap.js'], ['app.js', 'stages.js'], ['app.js', 'wombat.js'],
  ['home.js', 'home-data.js'], ['home.js', 'electorates.js'], ['home.js', 'money-map.js'],
]

/** Write each MODULE_STAMPS module's content hash into its importer; returns the importers that were stale. */
function stampModules({ check }) {
  const stale = []
  for (const importer of [...new Set(MODULE_STAMPS.map(([i]) => i))]) {
    const path = join(PUBLIC, importer)
    const before = readFileSync(path, 'utf8')
    let after = before
    for (const [, mod] of MODULE_STAMPS.filter(([i]) => i === importer)) {
      // A site path or a relative one ("./labels.js": Node's tests resolve it too).
      const pattern = new RegExp(`(["'])(\\.?)/${mod.replace('.', '\\.')}(?:\\?v=[A-Za-z0-9._-]*)?\\1`, 'g')
      let hits = 0
      after = after.replace(pattern, (_, q, dot) => { hits += 1; return `${q}${dot}/${mod}?v=${hashOf(mod)}${q}` })
      if (!hits) {
        console.error(`stamp_assets: ${importer} no longer imports /${mod}; update MODULE_STAMPS.`)
        process.exit(1)
      }
    }
    if (after !== before) {
      stale.push(importer)
      if (!check) writeFileSync(path, after)
    }
  }
  return stale
}

// Keep the homepage's first-render chrome identical to the application shell.
// Both documents then use navigation.js for the same menus and interactions.
function syncHomeChrome(html, shell) {
  const header = shell.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0]
  const drawer = shell.match(/<dialog class="nav-drawer"[\s\S]*?<\/dialog>/)?.[0]
  const footer = shell.match(/<footer>[\s\S]*?<\/footer>/)?.[0]
  if (!header || !drawer || !footer) throw new Error('Shared site chrome is missing from index.html')
  for (const [part, content] of [['header', `${header}\n${drawer}`], ['footer', footer]]) {
    const pattern = new RegExp(`<!-- site-${part}:start -->[\\s\\S]*?<!-- site-${part}:end -->`)
    if (!pattern.test(html)) throw new Error(`Homepage site-${part} markers are missing`)
    html = html.replace(pattern, () => `<!-- site-${part}:start -->\n${content}\n<!-- site-${part}:end -->`)
  }
  return html
}

function stamp({ check }) {
  buildMethods({ check })
  buildSpaShell({ check })
  // Modules first: their stamps change app.js and home.js, which are hashed below.
  const staleModules = stampModules({ check })
  const before = readFileSync(INDEX, 'utf8')
  const hashes = Object.fromEntries(STAMPED.map((f) => [f, hashOf(f)]))
  let hits = 0
  const after = before.replace(
    new RegExp(`/(${STAMPED.map((f) => f.replace('.', '\\.')).join('|')})\\?v=[A-Za-z0-9._-]*`, 'g'),
    (_, file) => {
      hits += 1
      return `/${file}?v=${hashes[file]}`
    },
  )
  if (hits < STAMPED.length) {
    console.error(
      `stamp_assets: expected a ?v= reference for each of ${STAMPED.join(', ')} in index.html, found ${hits}.`,
    )
    process.exit(1)
  }
  const communityPath = join(PUBLIC, 'community.html')
  const communityBefore = readFileSync(communityPath, 'utf8')
  // The community page wears the site masthead, drawer and footer, synced from index.html as home.html's are.
  const communityAfter = syncHomeChrome(communityBefore, after).replace(/\/(style\.css|ui-controls\.css|community\.css|community\.js|navigation\.js|quick-search\.js)(?:\?v=[A-Za-z0-9._-]*)?(?=")/g, (_, file) => `/${file}?v=${hashOf(file)}`)
  if (!check && communityAfter !== communityBefore) writeFileSync(communityPath, communityAfter)
  const workbenchPath = join(PUBLIC, 'ui-workbench.html')
  const workbenchBefore = readFileSync(workbenchPath, 'utf8')
  const workbenchAfter = workbenchBefore.replace(/\/(style\.css|ui-controls\.css|ui-source\.css|ui-source\.js|ui-workbench\.css|ui-workbench\.js)\?v=[A-Za-z0-9._-]*/g, (_, file) => `/${file}?v=${hashOf(file)}`)
  if (!check && workbenchAfter !== workbenchBefore) writeFileSync(workbenchPath, workbenchAfter)
  const homePath = join(PUBLIC, 'home.html')
  const homeBefore = readFileSync(homePath, 'utf8')
  const homeAfter = syncHomeChrome(homeBefore, after).replace(/\/(style\.css|ui-controls\.css|ui-source\.css|ui-source\.js|home\.css|home\.js|navigation\.js|quick-search\.js|analytics\.js|events\.js|gtm\.js)\?v=[A-Za-z0-9._-]*/g, (_, file) => `/${file}?v=${hashOf(file)}`)
  if (!check && homeAfter !== homeBefore) writeFileSync(homePath, homeAfter)
  if (check) {
    if (staleModules.length || homeAfter !== homeBefore || after !== before || communityAfter !== communityBefore || workbenchAfter !== workbenchBefore) {
      console.error('stamp_assets: entry-page stamps or shared chrome are stale — run `node scripts/stamp_assets.mjs`.')
      process.exit(1)
    }
    console.log('stamp_assets: stamps are current.')
    return
  }
  if (after !== before) writeFileSync(INDEX, after)
  for (const f of STAMPED) console.log(`  stamp ${f.padEnd(38)} v=${hashes[f]}`)
  console.log(after === before ? 'stamp_assets: already current.' : 'stamp_assets: index.html updated.')
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2)
  if (args.includes('--fonts')) await refreshFonts()
  stamp({ check: args.includes('--check') })
}
