#!/usr/bin/env node
/**
 * Content-hash stamp the portal's un-hashed entry assets, so public/_headers
 * can serve them immutable.
 *
 * portal/public/index.html references /app.js?v=<hash> and /style.css?v=<hash>.
 * This rewrites both stamps from the bytes on disk. A new release is then a new
 * URL, and a returning visitor picks it up on the first request instead of
 * sitting on a year-old cache entry.
 *
 *   node scripts/stamp_assets.mjs           # stamp (what `npm run deploy` runs)
 *   node scripts/stamp_assets.mjs --check   # exit 1 if the stamps are stale
 *   node scripts/stamp_assets.mjs --fonts   # re-pull the self-hosted webfonts
 *
 * WHY IT MUST RUN: `wrangler deploy` on its own ships an unstamped index.html
 * against immutable Cache-Control. Deploy with `npm run deploy`, never by hand.
 *
 * The modules app.js import()s at runtime (money-map.js, statemap.js, quiz.js,
 * ...) are fetched by bare path from inside app.js, so they cannot be stamped
 * from here; _headers gives them max-age=300 + a day of stale-while-revalidate
 * instead. Stamping them too would mean rewriting app.js at deploy time.
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PUBLIC = join(ROOT, 'portal', 'public')
const INDEX = join(PUBLIC, 'index.html')

/** Assets referenced from index.html with a ?v= stamp. */
const STAMPED = ['app.js', 'style.css']

const hashOf = (file) =>
  createHash('sha256').update(readFileSync(join(PUBLIC, file))).digest('hex').slice(0, 10)

// --- webfonts ---------------------------------------------------------------
// Self-hosting is what removed ~2.3s of render blocking (a serial round trip to
// fonts.googleapis.com just to learn the fonts.gstatic.com URLs) and two origins
// from the CSP. Google still owns the upstream files, so this refreshes them
// from the same CSS2 request the old <link> made, using a modern Chrome UA so
// the API answers with woff2.
const FONT_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;0,900;1,400' +
  '&family=Public+Sans:wght@400..700&display=swap'
const FONT_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
// Cyrillic is dropped on purpose: it is ~90 KB of repo for codepoints Hansard
// does not use, and the serif/sans fallbacks cover it if it ever appears.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'vietnamese'])
const FILE_STEM = { Merriweather: 'merriweather', 'Public Sans': 'public-sans' }
// The faces preloaded from index.html: the first serif and the first sans.
const PRELOAD = ['merriweather-normal-latin.woff2', 'public-sans-normal-latin.woff2']

const FONTS_BEGIN = '<!-- fonts:begin (generated by scripts/stamp_assets.mjs --fonts) -->'
const FONTS_END = '<!-- fonts:end -->'

async function refreshFonts() {
  const css = await (await fetch(FONT_CSS_URL, { headers: { 'user-agent': FONT_UA } })).text()
  const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)]
  if (!blocks.length) throw new Error('no @font-face blocks in the Google Fonts response')

  const dir = join(PUBLIC, 'fonts')
  mkdirSync(dir, { recursive: true })
  const faces = []
  const seen = new Set()
  for (const [, subset, decl] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue
    const family = /font-family:\s*'([^']+)'/.exec(decl)[1]
    const style = /font-style:\s*(\w+)/.exec(decl)[1]
    const src = /url\((https:\/\/[^)]+)\)/.exec(decl)[1]
    const range = /unicode-range:\s*([^;]+);/.exec(decl)[1].trim().replace(/,\s+/g, ',')
    const file = `${FILE_STEM[family]}-${style}-${subset}.woff2`
    if (seen.has(file)) continue
    seen.add(file)
    // Variable fonts: one file serves the whole axis. Merriweather's is
    // 400-900, Public Sans's 400-700; style.css uses 400/600/700.
    const weight = family === 'Merriweather' ? '400 900' : '400 700'
    const bytes = Buffer.from(await (await fetch(src, { headers: { 'user-agent': FONT_UA } })).arrayBuffer())
    writeFileSync(join(dir, file), bytes)
    faces.push({ family, style, weight, file, range, size: bytes.length })
  }
  for (const stale of readdirSync(dir)) {
    if (stale.endsWith('.woff2') && !seen.has(stale)) unlinkSync(join(dir, stale))
  }
  for (const want of PRELOAD) {
    if (!seen.has(want)) throw new Error(`preloaded face ${want} is no longer served by Google`)
  }

  const block = [
    FONTS_BEGIN,
    ...PRELOAD.map(
      (f) => `<link rel="preload" as="font" type="font/woff2" crossorigin href="/fonts/${f}">`,
    ),
    '<style>',
    ...faces.map(
      ({ family, style, weight, file, range }) =>
        `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
        `font-display:swap;src:url(/fonts/${file}) format('woff2');unicode-range:${range}}`,
    ),
    '</style>',
    FONTS_END,
  ].join('\n')

  const html = readFileSync(INDEX, 'utf8')
  const start = html.indexOf(FONTS_BEGIN)
  const end = html.indexOf(FONTS_END)
  if (start < 0 || end < 0) throw new Error('fonts:begin/fonts:end markers missing from index.html')
  writeFileSync(INDEX, html.slice(0, start) + block + html.slice(end + FONTS_END.length))
  for (const f of faces) console.log(`  font  ${f.file.padEnd(38)} ${String(f.size).padStart(7)} bytes`)
}

// --- stamping ---------------------------------------------------------------

function stamp({ check }) {
  const before = readFileSync(INDEX, 'utf8')
  const hashes = Object.fromEntries(STAMPED.map((f) => [f, hashOf(f)]))
  let hits = 0
  const after = before.replace(
    new RegExp(`/(${STAMPED.map((f) => f.replace('.', '\\.')).join('|')})\\?v=[A-Za-z0-9._-]*`, 'g'),
    (_, file) => {
      hits += 1
      return `/${file}?v=${hashes[file]}`
    },
  )
  if (hits < STAMPED.length) {
    console.error(
      `stamp_assets: expected a ?v= reference for each of ${STAMPED.join(', ')} in index.html, found ${hits}.`,
    )
    process.exit(1)
  }
  if (check) {
    if (after !== before) {
      console.error('stamp_assets: index.html stamps are stale — run `node scripts/stamp_assets.mjs`.')
      process.exit(1)
    }
    console.log('stamp_assets: stamps are current.')
    return
  }
  if (after !== before) writeFileSync(INDEX, after)
  for (const f of STAMPED) console.log(`  stamp ${f.padEnd(38)} v=${hashes[f]}`)
  console.log(after === before ? 'stamp_assets: already current.' : 'stamp_assets: index.html updated.')
}

const args = process.argv.slice(2)
if (args.includes('--fonts')) await refreshFonts()
stamp({ check: args.includes('--check') })
